(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
  const API = () => (window.CAF_CAE_CONFIG && window.CAF_CAE_CONFIG.API_URL) || 'https://api.cafcae.it';
  const token = () => localStorage.getItem('caf_cae_v12_token') || localStorage.getItem('caf_cae_token') || '';
  const esc = (v) => String(v ?? '').replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const euro = (v) => new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0));
  const fmt = (d) => { if(!d) return '--'; const x=new Date(d); return isNaN(x)?String(d):x.toLocaleDateString('it-IT'); };
  const pct = (n) => Math.max(0, Math.min(100, Number(n||0)));
  const today = () => new Date().toISOString().slice(0,10);
  const uid = () => 'ui-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
  const state = { mounted:false, page:'dashboard', detail:null, loading:false, data:{ practices:[], clients:[], users:[], memberships:[], notifications:[], teamMembers:[], credit:{ledger:[],balance:0}, packages:[] }, session:null, search:'' };

  async function api(path, opts={}){
    const headers = { ...(opts.headers||{}) };
    if (token()) headers.Authorization = 'Bearer ' + token();
    if (opts.json !== undefined) { headers['Content-Type']='application/json'; opts.body = JSON.stringify(opts.json); }
    const res = await fetch(API()+path, { ...opts, headers });
    const text = await res.text();
    let data; try { data = text ? JSON.parse(text) : {}; } catch { data = { ok:false, raw:text }; }
    if (!res.ok) throw new Error(data.error || data.message || text || ('HTTP '+res.status));
    return data;
  }
  function readSession(){
    try { const s=JSON.parse(localStorage.getItem('caf_cae_v12_session')||'null'); if(s) return s; } catch {}
    return state.session || null;
  }
  async function loadSession(){
    const s = readSession();
    if (!token() || !s) return null;
    try { const me = await api('/api/me'); state.session = me.user || me.session || s; }
    catch { state.session = s; }
    return state.session;
  }
  async function loadData(){
    if (!token()) return;
    state.loading = true;
    try {
      const sess = state.session || readSession() || {};
      const calls = [
        api('/api/practices').catch(e=>({ practices:[], error:e.message })),
        api('/api/v22/clients').catch(e=>({ clients:[] })),
        api('/api/v22/membership/results').catch(e=>({ results:[], memberships:[] })),
        api('/api/v22/notifications').catch(e=>({ notifications:[] })),
        api('/api/v22/team-members').catch(e=>({ members:[], team_members:[] })),
        api('/api/v22/commercialista/packages').catch(e=>({ packages:[] }))
      ];
      if ((sess.role||'') === 'admin') calls.push(api('/api/admin/users').catch(e=>({ users:[] })));
      else calls.push(Promise.resolve({ users:[] }));
      if ((sess.role||'') === 'agent' && sess.email) calls.push(api('/api/v22/agent/'+encodeURIComponent(sess.email)+'/credit').catch(e=>({ ledger:[], balance:0 })));
      else calls.push(Promise.resolve({ ledger:[], balance:0 }));
      const [pr, cl, mem, not, tm, packs, users, credit] = await Promise.all(calls);
      state.data.practices = pr.practices || pr.pratiche || pr.practice || [];
      state.data.clients = cl.clients || [];
      state.data.memberships = mem.results || mem.memberships || mem.membership_results || [];
      state.data.notifications = not.notifications || [];
      state.data.teamMembers = tm.members || tm.team_members || tm.rows || [];
      state.data.packages = packs.packages || [];
      state.data.users = users.users || [];
      state.data.credit = credit || { ledger:[], balance:0 };
    } finally { state.loading=false; }
  }
  const roleLabel = r => ({admin:'Amministratore',agent:'Agente',bangla:'Team Bangla',italy:'Team Italy',commercialista:'Commercialista'}[String(r||'').toLowerCase()] || r || 'Utente');
  const roleName = r => ({admin:'Admin',agent:'Agente',bangla:'Team Bangla',italy:'Team Italy',commercialista:'Commercialista'}[String(r||'').toLowerCase()] || r || '--');
  function owner(p){ return String(p.current_owner||p.currentOwner||p.ownerRole||p.assigned_team||p.assignedTeam||p.route_team||p.routeTeam||'').toLowerCase(); }
  function watchers(p){ const w=p.watchers||p.visibility||[]; return Array.isArray(w)?w.map(x=>String(x).toLowerCase()):[]; }
  function clientName(p){
    const c = p.client || p.client_data || {};
    return p.client_name || p.client || [c.firstName,c.lastName].filter(Boolean).join(' ') || [c.first_name,c.last_name].filter(Boolean).join(' ') || p.name || p.customer_name || '--';
  }
  function serviceName(p){ return p.service_title || p.serviceTitle || p.service || p.service_key || p.type || 'Pratica'; }
  function code(p){ return p.code || p.pratica_code || p.id || '--'; }
  function progressVal(p){ return pct(p.progress || p.workflow_progress || (String(p.status||'').toLowerCase().includes('complet')?100:25)); }
  function statusClass(s){ s=String(s||'').toLowerCase(); if(s.includes('complet')||s.includes('approv')||s.includes('attiva'))return'green'; if(s.includes('manc')||s.includes('integr')||s.includes('attesa'))return'orange'; if(s.includes('verif')||s.includes('lavor'))return'blue'; if(s.includes('respint')||s.includes('scad')||s.includes('non'))return'red'; return'gray'; }
  function pill(text, cls){ return `<span class="v26-pill ${cls||statusClass(text)}">${esc(text||'--')}</span>`; }
  function progress(n){ return `<div class="v26-progress"><i style="--p:${pct(n)}%"></i></div>`; }
  function rolePractices(role=state.session?.role){
    const email=String(state.session?.email||'').toLowerCase();
    const rows=[...(state.data.practices||[])];
    if(role==='admin') return rows;
    if(role==='agent') return rows.filter(p => String(p.agent_email||p.agentEmail||p.created_by||'').toLowerCase()===email || String(p.agent?.email||'').toLowerCase()===email);
    if(role==='bangla') return rows.filter(p => owner(p)==='bangla' || watchers(p).includes('bangla') || !owner(p));
    if(role==='italy') return rows.filter(p => owner(p)==='italy' || String(p.assigned_team||p.assignedTeam||'').toLowerCase()==='italy');
    if(role==='commercialista') return rows.filter(p => owner(p)==='commercialista' || watchers(p).includes('commercialista'));
    return rows;
  }
  function roleClients(role=state.session?.role){
    const email=String(state.session?.email||'').toLowerCase();
    let clients=[...(state.data.clients||[])];
    if(!clients.length){
      const map=new Map();
      rolePractices(role).forEach(p=>{ const key=(p.client_id||p.email||p.client_email||clientName(p)||code(p)); if(!map.has(key)) map.set(key,{ name:clientName(p), email:p.email||p.client_email||p.client?.email, phone:p.phone||p.client?.phone, cf:p.cf||p.client?.cf, lastPractice:code(p), created_by:p.created_by, agent_email:p.agent_email||p.agentEmail }); });
      clients=[...map.values()];
    }
    if(role==='agent') clients=clients.filter(c=>String(c.agent_email||c.created_by||c.owner_email||'').toLowerCase()===email || !c.created_by);
    if(role==='italy') { const names=new Set(rolePractices(role).map(p=>clientName(p))); clients=clients.filter(c=>names.has(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' '))); }
    return clients;
  }
  function kpis(role){ const ps=rolePractices(role); const all=state.data.practices||[]; const users=state.data.users||[]; const memberships=state.data.memberships||[]; const clients=roleClients(role); const credit=state.data.credit||{};
    if(role==='admin') return [
      ['Pratiche totali', all.length, 'backend live','fa-file-lines','green'], ['Agenti attivi', users.filter(u=>u.role==='agent'&&u.active!==false).length, '+ live','fa-users','orange'], ['Membri attivi', memberships.filter(m=>/attiv|approv/i.test(m.status||m.result||'')).length, '+ membership','fa-crown','purple'], ['Team Bangla in coda', all.filter(p=>owner(p)==='bangla'||!owner(p)).length, '+ workflow','fa-flag','blue'], ['Team Italy in coda', all.filter(p=>owner(p)==='italy').length, '+ workflow','fa-paper-plane','red'], ['Incassi mese', euro(all.reduce((s,p)=>s+Number(p.cost||p.amount||p.price||0),0)), '+ live','fa-coins','blue'] ];
    if(role==='agent') return [ ['Pratiche aperte', ps.filter(p=>!/complet/i.test(p.status||'')).length,'live','fa-file-lines','blue'], ['Pratiche complete', ps.filter(p=>/complet/i.test(p.status||'')).length,'live','fa-circle-check','green'], ['Membership attive', memberships.length,'live','fa-crown','orange'], ['Commissioni mese', euro(ps.reduce((s,p)=>s+Math.max(0,Number(p.cost||0)-Number(p.cafCost||p.caf_cost||0)),0)),'profitto','fa-percent','red'], ['Wallet disponibile', euro(credit.balance||0),'credito','fa-wallet','blue'], ['Clienti salvati', clients.length,'server','fa-users','green'] ];
    if(role==='bangla') return [ ['Nuove da agenti', ps.filter(p=>owner(p)==='bangla'||!owner(p)).length,'da controllare','fa-file-circle-plus','blue'], ['In verifica documenti', ps.filter(p=>/verif|doc/i.test(p.status||p.documentStatus||'')).length,'live','fa-magnifying-glass','red'], ['Documenti mancanti', ps.filter(p=>/manc|missing/i.test(p.documentStatus||p.status||'')).length,'richieste','fa-triangle-exclamation','orange'], ['Pronte per Italy', ps.filter(p=>progressVal(p)>=45 && owner(p)==='bangla').length,'autorizza','fa-paper-plane','blue'], ['Membership', memberships.length,'risultati','fa-crown','purple'], ['Clienti', clients.length,'database','fa-users','green'] ];
    if(role==='italy') return [ ['Assegnate', ps.length,'ricevute','fa-folder','blue'], ['In revisione', ps.filter(p=>/verif|revision|lavor/i.test(p.status||'')).length,'oggi','fa-clock','orange'], ['Da completare', ps.filter(p=>!/complet/i.test(p.status||'')).length,'workflow','fa-clipboard-check','green'], ['Membership esiti', memberships.length,'da gestire','fa-crown','purple'], ['Completate oggi', ps.filter(p=>/complet/i.test(p.status||'')).length,'done','fa-check-circle','green'], ['Documenti', ps.reduce((s,p)=>s+Number(p.files_count||0),0),'upload','fa-file-arrow-up','blue'] ];
    return [ ['Clienti attivi', clients.length,'server','fa-users','green'], ['Pratiche fiscali', ps.length,'studio','fa-folder','orange'], ['Fatture emesse', 0,'reale','fa-file-invoice','green'], ['Scadenze oggi', 0,'reale','fa-calendar-days','red'], ['Incassi mese', euro(ps.reduce((s,p)=>s+Number(p.cost||0),0)),'live','fa-coins','blue'], ['Membership business', memberships.length,'aziende','fa-crown','orange'] ];
  }
  function navFor(role){
    const common=[['dashboard','Dashboard','fa-house']];
    const map={
      admin:[...common,['users','Utenti & Ruoli','fa-user-shield'],['agents','Agenti','fa-users'],['bangla','Team Bangla','fa-circle'],['italy','Team Italy','fa-circle'],['commercialista','Commercialista','fa-building-columns'],['membership','Membership','fa-crown'],['practices','Pratiche','fa-file-lines'],['credit','Credito agenti','fa-coins'],['documents','Documenti','fa-folder'],['tickets','Tickets','fa-headset'],['reports','Report','fa-chart-line'],['settings','Impostazioni','fa-gear']],
      agent:[...common,['create','Crea pratica','fa-file-circle-plus'],['clients','I miei clienti','fa-users'],['practices','I miei ordini','fa-box'],['membership','Membership','fa-crown'],['wallet','Wallet','fa-wallet'],['commissioni','Commissioni','fa-chart-column'],['documents','Documenti','fa-folder'],['tickets','Supporto','fa-headset']],
      bangla:[...common,['agent-inbox','Nuove da Agenti','fa-file-import'],['verify','Verifica documenti','fa-circle-check'],['clients','Clienti','fa-users'],['practices','Pratiche','fa-file-lines'],['transfers','Trasferimenti','fa-paper-plane'],['membership','Membership','fa-crown'],['commercialista-lead','Commercialista lead','fa-building-columns'],['daily','Report giornaliero','fa-calendar-check'],['tickets','Ticket Admin','fa-comments']],
      italy:[...common,['assigned','Pratiche assegnate','fa-folder-open'],['review730','730 Review','fa-id-card'],['complete','Da completare','fa-clipboard-check'],['documents','Documenti','fa-file-arrow-up'],['membership','Membership esiti','fa-crown'],['tickets','Ticket','fa-headset'],['profile','Profilo & Salary','fa-user']],
      commercialista:[...common,['clients','Clienti','fa-users'],['company-new','Nuovo cliente / ditta','fa-plus'],['sales','Vendite e incassi','fa-chart-line'],['practices','Pratiche','fa-folder'],['invoices','Fatturazione','fa-file-invoice'],['f24','F24 e contributi','fa-building-columns'],['employees','Dipendenti','fa-users-gear'],['documents','Documenti','fa-folder-open'],['messages','Comunicazioni','fa-envelope'],['deadlines','Scadenze','fa-calendar'],['packages','Piani e pagamenti','fa-layer-group'],['reports','Report','fa-chart-pie']]
    };
    return map[role]||common;
  }
  function hero(){
    const role=state.session?.role||'admin';
    const data={
      admin:['Centro operativo totale','Gestisci pratiche, team, vendite, commissioni e tutte le operazioni in un unico pannello sicuro.'],
      agent:['Il tuo lavoro, più valore per le persone','Crea nuove pratiche, gestisci clienti, segui membership, credito e risultati in tempo reale.'],
      bangla:['Team Bangla Control Center','Ricevi ordini dagli agenti, verifica documenti, gestisci clienti, autorizza e trasferisci a Team Italy.'],
      italy:['Team Italy','Completa, verifica e finalizza le pratiche ricevute da Team Bangla, con qualità e ricevute.'],
      commercialista:['Area Commercialista','Gestisci clienti, ditte, pratiche fiscali, contabilità, documenti e adempimenti.']
    }[role]||['CAF CAE Pro','Gestionale operativo'];
    const actions = role==='admin' ? `${btn('Crea pratica','orange','data-page="create"')} ${btn('Nuovo utente','blue','data-page="users"')} ${btn('Nuova membership','purple','data-page="membership"')}` : role==='agent' ? `${btn('Nuova pratica','orange','data-page="create"')} ${btn('Nuova membership','blue','data-page="membership"')}` : role==='bangla' ? `${btn('Nuova pratica','orange','data-page="create"')} ${btn('Nuovo cliente','blue','data-page="clients"')} ${btn('Report giornaliero','green','data-page="daily"')}` : role==='italy' ? `${btn('Apri pratica','orange','data-page="assigned"')} ${btn('Carica ricevuta','blue','data-page="documents"')} ${btn('Ritorna a Bangla','light','data-page="assigned"')}` : `${btn('Nuovo cliente / ditta','blue','data-page="company-new"')} ${btn('Nuova pratica fiscale','orange','data-page="practices"')} ${btn('F24 e contributi','green','data-page="f24"')}`;
    return `<section class="v26-hero"><div><span class="v26-kicker"><i class="fa-solid fa-circle"></i> CAF CAE Pro</span><h1>${esc(data[0])}</h1><p>${esc(data[1])}</p></div><div class="v26-hero-actions">${actions}</div></section>`;
  }
  function btn(label, cls='light', attrs=''){ return `<button class="v26-btn ${cls}" ${attrs}>${label.includes('<')?label:esc(label)}</button>`; }
  function metricCard([label,value,sub,icon,cls]){ return `<article class="v26-card v26-metric ${cls||''}"><div class="v26-ico"><i class="fa-solid ${icon||'fa-chart-line'}"></i></div><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(sub)}</small></article>`; }
  function tableRows(rows, limit=8){
    if(!rows.length) return `<tr><td colspan="8"><div class="v26-empty">Nessun dato reale trovato. Crea una pratica o sincronizza dal backend.</div></td></tr>`;
    return rows.slice(0,limit).map(p=>`<tr data-filter="${esc((code(p)+' '+clientName(p)+' '+serviceName(p)).toLowerCase())}"><td><b>${esc(code(p))}</b></td><td>${esc(clientName(p))}</td><td>${esc(serviceName(p))}</td><td>${esc(roleName(owner(p)||'bangla'))}</td><td>${pill(p.status||p.workflow_status||'Nuova')}</td><td>${esc(p.document_status||p.documentStatus||'--')}</td><td>${progress(progressVal(p))}</td><td>${btn('Apri','light',`data-detail="${esc(p.id||p.code)}"`)}</td></tr>`).join('');
  }
  function practicesTable(title, subtitle, rows, filter=true){
    return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div>${filter?`<div class="v26-search" style="max-width:310px"><i class="fa-solid fa-search"></i><input data-local-search placeholder="Cerca cliente, pratica..."></div>`:''}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Codice</th><th>Cliente</th><th>Servizio</th><th>Team</th><th>Stato</th><th>Docs</th><th>Avanzamento</th><th>Azioni</th></tr></thead><tbody>${tableRows(rows,20)}</tbody></table></div></section>`;
  }
  function membershipPanel(){ const rows=state.data.memberships||[]; const active=rows.filter(m=>/attiv|approv|idoneo/i.test(m.status||m.result||'')).length; const pending=rows.filter(m=>/attesa|revision/i.test(m.status||m.result||'')).length; const bad=rows.filter(m=>/scad|respint|non/i.test(m.status||m.result||'')).length; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Risultati Membership</h2><p>Stato reale delle membership salvate nel backend.</p></div>${btn('Vedi dettagli','light','data-page="membership"')}</div><div style="display:flex;gap:24px;align-items:center;flex-wrap:wrap"><div class="v26-donut"><span>${rows.length}<small>Totali</small></span></div><div style="display:grid;gap:10px;min-width:210px"><b>Attive: ${active}</b><b>In revisione: ${pending}</b><b>Non idonee/scadute: ${bad}</b><b>Da rinnovare: ${rows.filter(m=>/rinnov/i.test(m.status||'')).length}</b></div></div></section>`; }
  function workflowPanel(){ const all=state.data.practices||[]; const inserted=all.length, bangla=all.filter(p=>owner(p)==='bangla'||!owner(p)).length, italy=all.filter(p=>owner(p)==='italy').length, done=all.filter(p=>/complet/i.test(p.status||'')).length; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Workflow pratiche</h2><p>Agent → Team Bangla → Team Italy → completata.</p></div></div><div class="v26-flow"><div class="step"><span class="num">1</span><div><b>${inserted}</b><p>Inserite</p></div></div><div class="step"><span class="num">2</span><div><b>${bangla}</b><p>Team Bangla</p></div></div><div class="step"><span class="num">3</span><div><b>${italy}</b><p>Team Italy</p></div></div><div class="step"><span class="num">4</span><div><b>${done}</b><p>Completate</p></div></div></div><div class="v26-mini-bars" style="margin-top:16px">${[22,35,28,50,45,60,40,72,58,80,65,90].map(h=>`<i style="--h:${h}%"></i>`).join('')}</div></section>`; }
  function quickActions(role){ const items = role==='admin' ? [['Nuova pratica','orange','create'],['Nuovo agente','blue','agents'],['Nuova membership','purple','membership'],['Assegna team','light','users']] : role==='agent' ? [['Nuova pratica','orange','create'],['Nuova membership','blue','membership'],['Nuovo cliente','light','clients'],['Carica documenti','light','documents'],['Calcola profitto','light','wallet'],['Verifica stato','light','practices']] : role==='bangla' ? [['Nuova pratica','orange','create'],['Nuovo cliente','blue','clients'],['Carica documenti','light','documents'],['Invia a Italy','green','transfers']] : role==='italy' ? [['Carica documenti','orange','documents'],['Nuova integrazione','blue','assigned'],['Ritorna a Bangla','light','assigned'],['Nuova nota','light','tickets']] : [['Nuovo cliente / ditta','blue','company-new'],['Nuova pratica fiscale','orange','practices'],['Emetti fattura','purple','invoices'],['F24 e contributi','green','f24']]; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Azioni rapide</h2><p>Operazioni principali</p></div></div><div class="v26-actions ${items.length>4?'two':''}">${items.map(([l,c,p])=>btn(`<i class="fa-solid fa-plus"></i> ${esc(l)}`,c,`data-page="${p}"`)).join('')}</div></section>`; }
  function activityPanel(){ const rows=(state.data.notifications||[]).slice(0,8); return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Attività recenti</h2><p>Movimenti e notifiche reali</p></div>${btn('Vedi tutte','light','data-page="notifications"')}</div><div class="v26-activity">${rows.map(n=>`<div class="v26-activity-item"><span class="dot"></span><div><b>${esc(n.title||n.type||'Notifica')}</b><span>${esc(n.message||n.description||'')}</span></div><small>${esc(fmt(n.created_at||n.createdAt))}</small></div>`).join('')||'<div class="v26-empty">Nessuna notifica reale.</div>'}</div></section>`; }
  function dashboard(){ const role=state.session?.role||'admin'; const ps=rolePractices(role); return `${hero()}<section class="v26-grid v26-metrics">${kpis(role).map(metricCard).join('')}</section>${role==='bangla'?banglaDashboard(ps):role==='italy'?italyDashboard(ps):role==='commercialista'?commercialistaDashboard(ps):role==='agent'?agentDashboard(ps):adminDashboard(ps)}`; }
  function adminDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${membershipPanel()}${practicesTable('Pratiche recenti','Ultime pratiche reali inserite nel sistema', ps)}</div><aside class="v26-grid">${quickActions('admin')}${activityPanel()}</aside></div>`; }
  function agentDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${membershipTable()}<div class="v26-layout wide"><div>${clientsCard()}</div><div>${statusBars(ps)}</div></div></div><aside class="v26-grid">${quickActions('agent')}${activityPanel()}</aside></div>`; }
  function banglaDashboard(ps){ return `<div class="v26-grid"><section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Flusso pratiche</h2><p>Primo controllo operativo prima di Team Italy.</p></div></div><div class="v26-flow"><div class="step"><span class="num">1</span><div><b>${ps.filter(p=>owner(p)==='bangla'||!owner(p)).length}</b><p>Da controllare</p></div></div><div class="step"><span class="num">2</span><div><b>${ps.filter(p=>/manc/i.test(p.documentStatus||p.status||'')).length}</b><p>Documenti mancanti</p></div></div><div class="step"><span class="num">3</span><div><b>${ps.filter(p=>progressVal(p)>=45).length}</b><p>Autorizzate</p></div></div><div class="step"><span class="num">4</span><div><b>${(state.data.practices||[]).filter(p=>owner(p)==='italy').length}</b><p>Trasferite a Italy</p></div></div></div></section><div class="v26-layout"><div>${practicesTable('Pratiche recenti','Elenco pratiche assegnate a Team Bangla',ps)}</div><aside class="v26-grid">${quickActions('bangla')}${membershipPanel()}${activityPanel()}</aside></div></div>`; }
  function italyDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${practicesTable('Pratiche assegnate a Team Italy','Qui trovi solo le pratiche autorizzate e trasferite da Team Bangla.',ps)}${workflowPanel()}</div><aside class="v26-grid">${membershipPanel()}${quickActions('italy')}${deadlinesCard(ps)}</aside></div>`; }
  function commercialistaDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid"><section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Nuovo cliente / nuova ditta</h2><p>Inserisci dati cliente o azienda con piano e documenti.</p></div>${btn('Salva e continua più tardi','light')}</div>${companyMiniForm()}</section><div class="v26-layout wide"><div>${deadlinesCard(ps)}</div><div>${documentsMissingCard()}</div></div>${practicesTable('Pratiche fiscali recenti','Pratiche reali collegate allo studio commercialista',ps)}</div><aside class="v26-grid">${quickActions('commercialista')}${packagesCard()}</aside></div>`; }
  function membershipTable(){ const rows=state.data.memberships||[]; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Risultati membership</h2><p>Controlla stato e risultati membership dei tuoi clienti.</p></div>${btn('Vedi tutte','light','data-page="membership"')}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Cliente</th><th>Tipo</th><th>Stato</th><th>Risultato</th><th>Scadenza</th><th>Team</th></tr></thead><tbody>${rows.slice(0,8).map(m=>`<tr><td>${esc(m.client_name||m.name||'--')}</td><td>${esc(m.type||m.membership_type||'Membership')}</td><td>${pill(m.status||'--')}</td><td>${pill(m.result||'--')}</td><td>${esc(fmt(m.expires_at||m.deadline))}</td><td>${esc(roleName(m.team_role||m.team))}</td></tr>`).join('')||'<tr><td colspan="6"><div class="v26-empty">Nessuna membership reale.</div></td></tr>'}</tbody></table></div></section>`; }
  function clientsCard(){ const rows=roleClients(); return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Clienti recenti</h2><p>Database clienti salvato sul server.</p></div>${btn('Vedi tutti','light','data-page="clients"')}</div>${rows.slice(0,5).map(c=>`<div class="v26-staff"><span class="v26-avatar">${esc((c.name||c.full_name||'C').slice(0,2).toUpperCase())}</span><div><b>${esc(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||'Cliente')}</b><span>${esc(c.cf||c.phone||c.email||'')}</span></div></div>`).join('')||'<div class="v26-empty">Nessun cliente reale.</div>'}</section>`; }
  function statusBars(ps){ const rows=[['Nuove',ps.filter(p=>/nuov/i.test(p.status||'')).length,20],['In lavorazione',ps.filter(p=>/lavor/i.test(p.status||'')).length,45],['In verifica',ps.filter(p=>/verif/i.test(p.status||'')).length,30],['Complete',ps.filter(p=>/complet/i.test(p.status||'')).length,85],['Sospese',ps.filter(p=>/sosp/i.test(p.status||'')).length,15]]; return `<section class="v26-card v26-section"><h2>Stato pratiche</h2><div style="display:grid;gap:15px;margin-top:15px">${rows.map(r=>`<div style="display:grid;grid-template-columns:110px 36px 1fr;gap:12px;align-items:center"><b>${r[0]}</b><span>${r[1]}</span>${progress(r[2])}</div>`).join('')}</div></section>`; }
  function deadlinesCard(ps){ return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Prossime scadenze</h2><p>Scadenze reali dalle pratiche.</p></div></div>${ps.slice(0,6).map(p=>`<div class="v26-staff"><span class="v26-avatar" style="background:#fee2e2;color:#b91c1c">${esc(String((p.deadline||p.scadenza||'--')).slice(8,10)||'--')}</span><div><b>${esc(code(p))}</b><span>${esc(clientName(p)+' · '+serviceName(p))}</span></div></div>`).join('')||'<div class="v26-empty">Nessuna scadenza reale.</div>'}</section>`; }
  function documentsMissingCard(){ return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Documenti mancanti</h2><p>Da caricare o richiedere al cliente.</p></div></div><div class="v26-empty">Seleziona una pratica per vedere i documenti mancanti reali.</div></section>`; }
  function packagesCard(){ const packs=state.data.packages||[]; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Piani Commercialista</h2><p>Pacchetti reali/configurabili.</p></div></div>${packs.map(p=>`<div class="v26-staff"><span class="v26-avatar"><i class="fa-solid fa-layer-group"></i></span><div><b>${esc(p.name||p.title)}</b><span>${euro(p.monthly_price||p.price||0)} / mese</span></div></div>`).join('')||'<div class="v26-empty">Nessun piano salvato.</div>'}</section>`; }
  function companyMiniForm(){ return `<form class="v26-form"><label>Nome<input placeholder="Mario"></label><label>Cognome<input placeholder="Bianchi"></label><label>Email<input placeholder="cliente@email.it"></label><label>Codice fiscale<input placeholder="BNCMRA..."></label><label>Telefono<input placeholder="+39..."></label><label>Tipo cliente<select><option>Persona fisica</option><option>Ditta individuale</option><option>Società</option></select></label><label class="wide">Indirizzo<input placeholder="Via Roma 123"></label><button class="v26-btn orange" type="button" data-page="company-new">Avanti</button></form>`; }
  function pageContent(){ const role=state.session?.role||'admin'; const ps=rolePractices(role); if(state.page==='dashboard') return dashboard(); if(state.page==='create'||state.page==='company-new') return createPage(role); if(state.page==='clients'||state.page==='agents'||state.page==='users') return clientsPage(role); if(state.page==='documents') return documentsPage(ps); if(state.page==='membership') return membershipPage(); if(state.page==='credit'||state.page==='wallet') return creditPage(); if(state.page==='daily') return dailyPage(); if(state.page==='tickets') return ticketsPage(); if(['practices','assigned','agent-inbox','verify','transfers','review730','complete'].includes(state.page)) return `${hero()}${practicesTable(state.page==='assigned'?'Pratiche assegnate':'Pratiche','Dati reali dal backend',ps)}`; if(state.page==='detail') return detailPage(state.detail); return `${hero()}${practicesTable('Dati reali','Modulo in costruzione collegato al backend',ps)}`; }
  function createPage(role){ const services=[['Modello 730','730','35','6'],['ISEE Ordinario','ISEE','25','4'],['NASpI','NASPI','30','5'],['Assegno Unico','AU','25','4'],['Permesso di Soggiorno','PDS','40','8'],['Ricongiungimento Familiare','RICONG','60','8'],['Cittadinanza Italiana','CITT','80','10'],['Apertura Partita IVA','PIVA','50','6']]; return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Crea nuova pratica</h2><p>Salva cliente, pratica e workflow direttamente nel backend. Agent → Team Bangla; Admin/Bangla possono scegliere team.</p></div></div><div class="v26-service-grid" id="v26Services">${services.map((s,i)=>`<button type="button" class="v26-service ${i===0?'active':''}" data-service="${esc(s[1])}" data-title="${esc(s[0])}" data-price="${s[2]}" data-caf="${s[3]}"><b>${esc(s[0])}</b><span>Prezzo cliente €${s[2]} · costo CAF €${s[3]}</span></button>`).join('')}</div><form class="v26-form" id="v26CreateForm" style="margin-top:18px"><input type="hidden" name="service" value="730"><input type="hidden" name="serviceTitle" value="Modello 730"><input type="hidden" name="price" value="35"><input type="hidden" name="cafCost" value="6"><label>Nome<input name="firstName" required></label><label>Cognome<input name="lastName" required></label><label>Email<input name="email"></label><label>Telefono<input name="phone"></label><label>Codice fiscale<input name="cf"></label><label>Team destinazione<select name="team"><option value="bangla">Team Bangla</option>${role==='admin'||role==='bangla'?'<option value="commercialista">Commercialista</option><option value="italy">Team Italy (solo admin/autorizzato)</option>':''}</select></label><label>Prezzo cliente<input name="clientPaid" type="number" value="35"></label><label>Costo CAF CAE<input name="cafCostInput" type="number" value="6"></label><label>Profitto agente<input name="profit" readonly value="29"></label><label class="wide">Note pratica<textarea name="note"></textarea></label><button class="v26-btn orange" type="submit"><i class="fa-solid fa-paper-plane"></i> Salva pratica nel backend</button></form></section>`; }
  function clientsPage(role){ const rows=roleClients(role); return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Clienti</h2><p>Archivio clienti server con auto-fill futuro.</p></div>${btn('Nuovo cliente','orange','data-page="create"')}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Nome</th><th>CF</th><th>Telefono</th><th>Email</th><th>Ultima pratica</th><th>Azione</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||'--')}</td><td>${esc(c.cf||'--')}</td><td>${esc(c.phone||'--')}</td><td>${esc(c.email||'--')}</td><td>${esc(c.lastPractice||'--')}</td><td>${btn('Apri','light')}</td></tr>`).join('')||'<tr><td colspan="6"><div class="v26-empty">Nessun cliente reale.</div></td></tr>'}</tbody></table></div></section>`; }
  function documentsPage(ps){ return `${hero()}${practicesTable('Documenti e allegati','Apri una pratica per caricare, vedere anteprima e scaricare documenti.', ps)}`; }
  function membershipPage(){ return `${hero()}${membershipPanel()}${membershipTable()}`; }
  function creditPage(){ const cr=state.data.credit||{}; const req=[]; return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Credito / Wallet</h2><p>Saldo, richieste e storico movimenti.</p></div>${state.session?.role==='agent'?btn('Richiedi credito','orange','id="v26CreditReq"'):''}</div><div class="v26-metrics v26-grid"><article class="v26-card v26-metric green"><div class="v26-ico"><i class="fa-solid fa-wallet"></i></div><span>Saldo disponibile</span><strong>${euro(cr.balance||0)}</strong><small>backend</small></article><article class="v26-card v26-metric orange"><div class="v26-ico"><i class="fa-solid fa-clock"></i></div><span>Movimenti</span><strong>${(cr.ledger||[]).length}</strong><small>storico</small></article></div></section>`; }
  function dailyPage(){ return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Report giornaliero team</h2><p>Invia il lavoro svolto ad Admin per monitoraggio.</p></div></div><form class="v26-form" id="v26DailyForm"><label>Pratiche controllate<input name="checked" type="number"></label><label>Completate<input name="done" type="number"></label><label>Documenti richiesti<input name="missing" type="number"></label><label class="wide">Note<textarea name="notes" required></textarea></label><button class="v26-btn green" type="submit">Invia report</button></form></section>`; }
  function ticketsPage(){ return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Ticket</h2><p>Problemi, richieste admin e comunicazioni operative.</p></div></div><form class="v26-form" id="v26TicketForm"><label>Oggetto<input name="subject" required></label><label>Pratica<input name="practice_code"></label><label>Destinatario<select name="target_role"><option value="admin">Admin</option><option value="bangla">Team Bangla</option><option value="italy">Team Italy</option><option value="commercialista">Commercialista</option></select></label><label class="wide">Messaggio<textarea name="message" required></textarea></label><button class="v26-btn orange" type="submit">Invia ticket</button></form></section>`; }
  async function filesFor(id){ try { return (await api('/api/practices/'+encodeURIComponent(id)+'/files')).files||[]; } catch { return []; } }
  function detailPage(id){ const p=(state.data.practices||[]).find(x=>String(x.id)===String(id)||String(x.code)===String(id)); if(!p) return `${hero()}<div class="v26-empty">Pratica non trovata</div>`; const hist=[...(p.workflow_events||p.workflowEvents||[]),...(p.team_history||p.teamHistory||[])].slice(0,8); return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>${esc(code(p))}</h2><p>${esc(clientName(p))} · ${esc(serviceName(p))}</p></div><div class="v26-hero-actions">${owner(p)==='bangla'||state.session?.role==='admin'?btn('Autorizza Team Italy','green',`data-authorize="${esc(p.id)}"`):''}${btn('Carica documenti','orange',`data-upload="${esc(p.id)}"`)}${btn('Carica ricevuta','blue',`data-upload-receipt="${esc(p.id)}"`)}</div></div><div class="v26-detail-grid"><div class="v26-card v26-section"><h3>Info cliente</h3><p><b>${esc(clientName(p))}</b></p><p>Email: ${esc(p.email||p.client?.email||'--')}</p><p>Tel: ${esc(p.phone||p.client?.phone||'--')}</p><p>CF: ${esc(p.cf||p.client?.cf||'--')}</p></div><div class="v26-card v26-section"><h3>Pratica</h3><p>Servizio: <b>${esc(serviceName(p))}</b></p><p>Owner: <b>${esc(roleName(owner(p)))}</b></p><p>Stato: ${pill(p.status||'Nuova')}</p><p>Documenti: ${esc(p.document_status||p.documentStatus||'--')}</p>${progress(progressVal(p))}<div id="v26Files" class="v26-doc-list" style="margin-top:18px"><div class="v26-empty">Caricamento allegati...</div></div></div><div class="v26-card v26-section"><h3>Timeline</h3><div class="v26-activity">${hist.map(h=>`<div class="v26-activity-item"><span class="dot"></span><div><b>${esc(h.action||h.message||'Update')}</b><span>${esc(h.by||h.actor_name||'Sistema')}</span></div><small>${esc(fmt(h.date||h.created_at))}</small></div>`).join('')||'<div class="v26-empty">Nessuna timeline</div>'}</div></div></div></section>`; }
  function shell(){ const sess=state.session||readSession()||{}; const role=sess.role||'admin'; const nav=navFor(role); return `<aside class="v26-sidebar"><div class="v26-brand"><span class="v26-logo-mark">C</span><div><strong>CAF CAE <span>Pro</span></strong><small>Servizi. Persone. Risultati.</small></div></div><div class="v26-user-mini"><span class="v26-avatar">${esc((sess.name||sess.email||role).slice(0,2).toUpperCase())}</span><div><b>${esc(sess.name||sess.email||'Utente')}</b><span>${esc(roleLabel(role))}</span></div></div><nav class="v26-nav"><div class="v26-nav-title">Menu operativo</div>${nav.map(([p,l,i])=>`<button data-page="${p}" class="${state.page===p?'active':''}"><i class="fa-solid ${i}"></i>${esc(l)}${p==='tickets'?'<span class="v26-badge">!</span>':''}</button>`).join('')}</nav><div class="v26-sidebar-footer"><b>CAF CAE Pro v26</b><br>UI nuova completa · backend live</div></aside><main class="v26-main"><header class="v26-topbar"><button class="v26-menu-toggle" id="v26Menu"><i class="fa-solid fa-bars"></i></button><div class="v26-titlebox"><b>${esc(titleForPage())}</b><p>${esc(subtitleForRole(role))}</p></div><div class="v26-search"><i class="fa-solid fa-search"></i><input id="v26GlobalSearch" value="${esc(state.search)}" placeholder="Cerca pratiche, utenti, documenti, clienti..."></div><div class="v26-top-actions"><button class="v26-icon"><i class="fa-regular fa-bell"></i><em>${state.data.notifications?.length||0}</em></button><button class="v26-icon"><i class="fa-regular fa-message"></i></button><button class="v26-icon"><i class="fa-regular fa-circle-question"></i></button><div class="v26-profile"><span class="v26-avatar">${esc((sess.name||role).slice(0,1).toUpperCase())}</span><div><b>${esc(sess.name||sess.email||'Utente')}</b><span>${esc(roleLabel(role))}</span></div></div></div></header><div class="v26-content" id="v26Content">${pageContent()}</div></main><input id="v26FileInput" type="file" multiple class="v26-hide">`; }
  function titleForPage(){ const p=state.page; const m={dashboard:'Dashboard',create:'Crea pratica',clients:'Clienti',practices:'Pratiche',documents:'Documenti',membership:'Membership Center',credit:'Credito agenti',wallet:'Wallet',tickets:'Ticket',daily:'Report giornaliero',detail:'Dettaglio pratica'}; return m[p]||p.replace(/-/g,' ').replace(/^./,c=>c.toUpperCase()); }
  function subtitleForRole(role){ return ({admin:'Panoramica generale del sistema CAF CAE Pro',agent:'Panoramica attività, clienti, pratiche e risultati',bangla:'Gestisci clienti, documenti e pratiche per Team Italy',italy:'Panoramica operativa del Team Italy',commercialista:'Gestisci il tuo studio professionale in modo semplice e sicuro'}[role]||'CAF CAE Pro'); }
  function render(){ const shellEl=$('#appShell'); if(!shellEl || shellEl.classList.contains('hidden') || !token() || !readSession()) return false; document.body.classList.add('cae-v26-active'); shellEl.classList.add('cae-v26-mounted'); let app=$('#caeV26App'); if(!app){ app=document.createElement('div'); app.id='caeV26App'; shellEl.appendChild(app); } app.innerHTML=shell(); if(state.detail) setTimeout(loadFilesIntoDetail,50); return true; }
  async function mount(){ if(state.mounted) return; const ok=await loadSession(); if(!ok) return; await loadData(); state.mounted=true; render(); }
  async function refresh(){ await loadSession(); await loadData(); render(); }
  async function loadFilesIntoDetail(){ const box=$('#v26Files'); if(!box || !state.detail) return; const files=await filesFor(state.detail); box.innerHTML = files.map(f=>`<div class="v26-doc"><i class="fa-solid fa-file-pdf"></i><div><b>${esc(f.file_name||f.name||'Documento')}</b><small>${esc(f.category||'Allegato')} · ${esc(f.uploaded_by_name||'')}</small></div><a class="v26-btn light" target="_blank" href="${API()}/api/files/${encodeURIComponent(f.id)}/preview?token=${encodeURIComponent(token())}">Anteprima</a><a class="v26-btn green" target="_blank" href="${API()}/api/files/${encodeURIComponent(f.id)}/download?token=${encodeURIComponent(token())}">Scarica</a></div>`).join('') || '<div class="v26-empty">Nessun allegato caricato. Usa “Carica documenti”.</div>'; }
  async function submitCreate(form){ const fd=new FormData(form); const service=fd.get('serviceTitle')||fd.get('service')||'Pratica'; const first=fd.get('firstName'), last=fd.get('lastName'); const team=fd.get('team')||'bangla'; const payload={ code:`CAF-${String(fd.get('service')||'PRATICA').toUpperCase()}-${new Date().getFullYear()}-${String((state.data.practices.length||0)+1).padStart(4,'0')}`, serviceTitle:service, service_key:fd.get('service'), service:service, current_owner:team, currentOwner:team, assigned_team:team, route_team:team, status:'Nuova', documentStatus:'Documenti mancanti', progress:15, cost:Number(fd.get('clientPaid')||fd.get('price')||0), cafCost:Number(fd.get('cafCostInput')||fd.get('cafCost')||0), client:{firstName:first,lastName:last,email:fd.get('email'),phone:fd.get('phone'),cf:fd.get('cf')}, client_name:[first,last].filter(Boolean).join(' '), email:fd.get('email'), phone:fd.get('phone'), cf:fd.get('cf'), note:fd.get('note') };
    await api('/api/v22/practices',{method:'POST',json:{practice:payload}}); await refresh(); state.page='dashboard'; render(); toast('Pratica salvata nel backend.'); }
  async function uploadFiles(id,isReceipt=false){ const inp=$('#v26FileInput'); inp.value=''; inp.onchange=async()=>{ if(!inp.files.length) return; const fd=new FormData(); [...inp.files].forEach(f=>fd.append('files',f)); fd.append('is_receipt', isReceipt?'true':'false'); fd.append('category', isReceipt?'Ricevuta':'Documento'); await api('/api/practices/'+encodeURIComponent(id)+'/files/upload',{method:'POST',body:fd}); toast('Documento caricato.'); await loadFilesIntoDetail(); await loadData(); render(); }; inp.click(); }
  async function authorize(id){ await api('/api/v22/practices/'+encodeURIComponent(id)+'/authorize',{method:'POST',json:{target:'italy'}}); toast('Pratica autorizzata e inviata a Team Italy.'); await refresh(); }
  async function dailyReport(form){ const fd=new FormData(form); await api('/api/v22/team/daily-report',{method:'POST',json:{team_role:state.session.role, checked:Number(fd.get('checked')||0), done:Number(fd.get('done')||0), missing:Number(fd.get('missing')||0), notes:fd.get('notes')}}); toast('Report inviato ad Admin.'); }
  async function ticket(form){ const fd=new FormData(form); await api('/api/v22/tickets',{method:'POST',json:{subject:fd.get('subject'), practice_code:fd.get('practice_code'), target_role:fd.get('target_role'), message:fd.get('message')}}); toast('Ticket inviato.'); }
  function toast(msg){ const t=$('#toast'); if(t){ t.textContent=msg; t.className='toast'; setTimeout(()=>t.classList.add('hidden'),2600); } else alert(msg); }
  document.addEventListener('click', e=>{
    const page=e.target.closest('[data-page]'); if(page){ e.preventDefault(); state.page=page.dataset.page; state.detail=null; render(); return; }
    const det=e.target.closest('[data-detail]'); if(det){ e.preventDefault(); state.page='detail'; state.detail=det.dataset.detail; render(); return; }
    const up=e.target.closest('[data-upload]'); if(up){ e.preventDefault(); uploadFiles(up.dataset.upload,false); return; }
    const rec=e.target.closest('[data-upload-receipt]'); if(rec){ e.preventDefault(); uploadFiles(rec.dataset.uploadReceipt,true); return; }
    const au=e.target.closest('[data-authorize]'); if(au){ e.preventDefault(); authorize(au.dataset.authorize); return; }
    if(e.target.closest('#v26Menu')) document.body.classList.toggle('v26-open');
    const svc=e.target.closest('.v26-service'); if(svc){ $$('.v26-service').forEach(x=>x.classList.remove('active')); svc.classList.add('active'); const form=$('#v26CreateForm'); if(form){ form.service.value=svc.dataset.service; form.serviceTitle.value=svc.dataset.title; form.price.value=svc.dataset.price; form.cafCost.value=svc.dataset.caf; form.clientPaid.value=svc.dataset.price; form.cafCostInput.value=svc.dataset.caf; form.profit.value=Number(svc.dataset.price||0)-Number(svc.dataset.caf||0); } }
  });
  document.addEventListener('input', e=>{ if(e.target.name==='clientPaid'||e.target.name==='cafCostInput'){ const f=$('#v26CreateForm'); if(f) f.profit.value=Number(f.clientPaid.value||0)-Number(f.cafCostInput.value||0); } if(e.target.matches('[data-local-search]')){ const q=e.target.value.toLowerCase(); $$('[data-filter]').forEach(r=>r.style.display=r.dataset.filter.includes(q)?'':'none'); } if(e.target.id==='v26GlobalSearch'){ state.search=e.target.value; }});
  document.addEventListener('submit', e=>{ if(e.target.id==='v26CreateForm'){ e.preventDefault(); submitCreate(e.target).catch(err=>toast(err.message)); } if(e.target.id==='v26DailyForm'){ e.preventDefault(); dailyReport(e.target).catch(err=>toast(err.message)); } if(e.target.id==='v26TicketForm'){ e.preventDefault(); ticket(e.target).catch(err=>toast(err.message)); } });
  window.CAF_CAE_V26_SYNC = refresh;
  window.CAF_CAE_V26_RENDER = render;
  const bootTimer=setInterval(()=>{ if(!state.mounted) mount().catch(()=>{}); else if(!$('#caeV26App')) render(); }, 800);
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>mount().catch(()=>{}),1200));
})();
