(() => {
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
  const API = () => (window.CAF_CAE_CONFIG && window.CAF_CAE_CONFIG.API_URL) || 'https://api.cafcae.it';
  const token = () => localStorage.getItem('caf_cae_v12_token') || localStorage.getItem('caf_cae_token') || '';
  const esc = (v) => String(v ?? '').replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const euro = (v) => new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0));
  const fmt = (d) => { if(!d) return '--'; const x=new Date(d); return isNaN(x)?String(d):x.toLocaleDateString('it-IT'); };
  const pct = (n) => Math.max(0, Math.min(100, Number(n||0)));
  const today = () => new Date().toISOString().slice(0,10);
  const uid = () => 'ui-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
  const state = { mounted:false, page:'dashboard', detail:null, loading:false, data:{ practices:[], clients:[], users:[], memberships:[], notifications:[], teamMembers:[], credit:{ledger:[],balance:0}, packages:[] }, session:null, search:'' };

  window.addEventListener('error', function(e){
    const msg = String(e.message || '');
    if(msg.includes('textContent') || msg.includes('Cannot set properties of null')){
      console.warn('CAF CAE v31 ignored old UI render error:', msg);
      try { setTimeout(forceRender, 60); } catch {}
      e.preventDefault();
      return true;
    }
  }, true);

  async function api(path, opts={}){
    const headers = { ...(opts.headers||{}) };
    if (token()) headers.Authorization = 'Bearer ' + token();
    if (opts.json !== undefined) { headers['Content-Type']='application/json'; opts.body = JSON.stringify(opts.json); }
    const res = await fetch(API()+path, { ...opts, headers });
    const text = await res.text();
    let data; try { data = text ? JSON.parse(text) : {}; } catch { data = { ok:false, raw:text }; }
    if (!res.ok) throw new Error(data.error || data.message || text || ('HTTP '+res.status));
    return data;
  }
  function readSession(){
    try { const s=JSON.parse(localStorage.getItem('caf_cae_v12_session')||'null'); if(s) return s; } catch {}
    return state.session || null;
  }
  async function loadSession(){
    const s = readSession();
    if (!token() || !s) return null;
    try { const me = await api('/api/me'); state.session = me.user || me.session || s; }
    catch { state.session = s; }
    return state.session;
  }
  function showLogin(message){
    document.body.classList.add('cae-v26-active','cae-v29-login-active');
    document.documentElement.classList.add('cae-v30-login-mode');
    document.body.style.overflow='hidden';
    let root = document.getElementById('caeV29LoginRoot');
    if(!root){
      root = document.createElement('div');
      root.id = 'caeV29LoginRoot';
      document.body.appendChild(root);
    }
    root.style.pointerEvents = 'auto';
    root.style.display = 'flex';
    root.innerHTML = `<div class="v29-login-shell">
      <div class="v29-login-card">
        <div class="v29-login-brand"><span>C</span><div><b>CAF CAE <em>Pro</em></b><small>Servizi. Persone. Risultati.</small></div></div>
        <h1>Accesso operativo</h1>
        <p>${esc(message || 'Entra nel gestionale CAF CAE Pro con il tuo account.')}</p>
        <form id="v31LoginForm" class="v29-login-form v31-login-form" autocomplete="off" spellcheck="false" novalidate>
          <label>Email o username<input id="v31LoginUser" name="cafcae_user_31" type="text" inputmode="email" autocomplete="off" autocorrect="off" autocapitalize="none" placeholder="Scrivi admin oppure italy@cafcae.it" required></label>
          <label>Password<input id="v31LoginPass" name="cafcae_pass_31" type="password" autocomplete="new-password" autocorrect="off" autocapitalize="none" placeholder="Scrivi password" required></label>
          <button id="v31LoginBtn" type="submit">Accedi alla dashboard</button>
        </form>
        <div class="v29-login-help">UI v32 attiva · login stabile · tasto Invio funzionante</div>
      </div>
    </div>`;
    root.querySelectorAll('input,button,textarea,select').forEach((el,i)=>{
      el.disabled=false; el.readOnly=false;
      el.removeAttribute('disabled'); el.removeAttribute('readonly');
      el.style.pointerEvents='auto'; el.style.userSelect='auto'; el.style.opacity='1';
      if(el.tagName==='INPUT'){
        el.setAttribute('autocomplete','off');
        el.setAttribute('data-lpignore','true');
        el.setAttribute('data-1p-ignore','true');
        el.setAttribute('data-form-type','other');
        el.name = 'cafcae_v31_' + i + '_' + Date.now();
      }
    });
    setTimeout(()=>{ const inp=root.querySelector('#v31LoginUser'); if(inp) { inp.focus(); inp.select?.(); } }, 120);
    const oldApp = document.getElementById('caeV26App');
    if(oldApp) oldApp.remove();
    state.mounted = false;
    return true;
  }
  async function handleLoginForm(form){
    const username = String((form.querySelector('#v31LoginUser')||form.querySelector('input[type="text"],input:not([type])'))?.value || '').trim();
    const password = String((form.querySelector('#v31LoginPass')||form.querySelector('input[type="password"]'))?.value || '');
    const btn = form.querySelector('button');
    if(btn){ btn.disabled = true; btn.textContent = 'Accesso...'; }
    try{
      if(!username || !password) throw new Error('Inserisci username/email e password.');
      let data = null;
      let lastError = '';
      if(window.CAF_CAE_API && typeof window.CAF_CAE_API.login === 'function'){
        try { data = await window.CAF_CAE_API.login(username, password); }
        catch(ex){ lastError = ex.message || String(ex); }
      }
      const body = { username, email: username, identifier: username, password };
      const endpoints = ['/api/auth/login','/api/login','/login'];
      if(!data){
        for (const ep of endpoints){
          try{
            const res = await fetch(API()+ep, {
              method:'POST',
              credentials:'include',
              headers:{ 'Content-Type':'application/json' },
              body: JSON.stringify(body)
            });
            const text = await res.text();
            let parsed = {}; try { parsed = text ? JSON.parse(text) : {}; } catch { parsed = { ok:false, raw:text }; }
            console.log('CAF CAE v31 login try', ep, res.status, parsed);
            if(res.ok && (parsed.token || parsed.access_token || parsed.jwt || parsed.user)){ data = parsed; break; }
            lastError = parsed.error || parsed.message || text || ('HTTP '+res.status);
          } catch(ex){ lastError = ex.message; }
        }
      }
      if(!data) throw new Error(lastError || 'Login backend non riuscito.');
      const tok = data.token || data.access_token || data.jwt || data.session?.access_token || '';
      if(tok){
        localStorage.setItem('caf_cae_v12_token', tok);
        localStorage.setItem('caf_cae_token', tok);
        try { if(window.CAF_CAE_API && typeof window.CAF_CAE_API.setToken==='function') window.CAF_CAE_API.setToken(tok); } catch {}
      }
      const u = data.user || data.profile || data.session?.user || data;
      if(!tok && !u) throw new Error('Login senza token/user. Controlla backend.');
      localStorage.setItem('caf_cae_v12_session', JSON.stringify({ id:u.id, email:u.email||username, username:u.username||username, name:u.name||u.full_name||username, role:u.role||'admin', phone:u.phone, office:u.office||'CAF CAE' }));
      state.session = { ...u, email:u.email||username, username:u.username||username, role:u.role||'admin' };
      const root = document.getElementById('caeV29LoginRoot');
      if(root) root.remove();
      document.body.classList.remove('cae-v29-login-active');
      document.documentElement.classList.remove('cae-v30-login-mode');
      document.body.style.overflow='';
      state.mounted = false;
      await refresh();
      await forceRender();
    }catch(err){
      showLogin(err.message || 'Accesso non riuscito. Controlla username e password.');
    }finally{
      if(btn){ btn.disabled = false; btn.textContent = 'Accedi alla dashboard'; }
    }
  }
  function performLogout(){
    try { if(window.CAF_CAE_API && typeof window.CAF_CAE_API.setToken === 'function') window.CAF_CAE_API.setToken(''); } catch {}
    ['caf_cae_v12_token','caf_cae_token','caf_cae_v12_session','caf_cae_v11_session','caf_cae_v8_session'].forEach(k=>localStorage.removeItem(k));
    sessionStorage.clear();
    state.session = null;
    state.mounted = false;
    state.page = 'dashboard';
    showLogin('Logout completato. Accedi di nuovo per continuare.');
    document.documentElement.classList.add('cae-v30-login-mode');
  }
  async function loadData(){
    if (!token()) return;
    state.loading = true;
    try {
      const sess = state.session || readSession() || {};
      const calls = [
        api('/api/practices').catch(e=>({ practices:[], error:e.message })),
        api('/api/v22/clients').catch(e=>({ clients:[] })),
        api('/api/v22/membership/results').catch(e=>({ results:[], memberships:[] })),
        api('/api/v22/notifications').catch(e=>({ notifications:[] })),
        api('/api/v22/team-members').catch(e=>({ members:[], team_members:[] })),
        api('/api/v22/commercialista/packages').catch(e=>({ packages:[] }))
      ];
      if ((sess.role||'') === 'admin') calls.push(api('/api/admin/users').catch(e=>({ users:[] })));
      else calls.push(Promise.resolve({ users:[] }));
      if ((sess.role||'') === 'agent' && sess.email) calls.push(api('/api/v22/agent/'+encodeURIComponent(sess.email)+'/credit').catch(e=>({ ledger:[], balance:0 })));
      else calls.push(Promise.resolve({ ledger:[], balance:0 }));
      const [pr, cl, mem, not, tm, packs, users, credit] = await Promise.all(calls);
      state.data.practices = pr.practices || pr.pratiche || pr.practice || [];
      state.data.clients = cl.clients || [];
      state.data.memberships = mem.results || mem.memberships || mem.membership_results || [];
      state.data.notifications = not.notifications || [];
      state.data.teamMembers = tm.members || tm.team_members || tm.rows || [];
      state.data.packages = packs.packages || [];
      state.data.users = users.users || [];
      state.data.credit = credit || { ledger:[], balance:0 };
    } finally { state.loading=false; }
  }
  const roleLabel = r => ({admin:'Amministratore',agent:'Agente',bangla:'Team Bangla',italy:'Team Italy',commercialista:'Commercialista'}[String(r||'').toLowerCase()] || r || 'Utente');
  const roleName = r => ({admin:'Admin',agent:'Agente',bangla:'Team Bangla',italy:'Team Italy',commercialista:'Commercialista'}[String(r||'').toLowerCase()] || r || '--');
  function owner(p){ return String(p.current_owner||p.currentOwner||p.ownerRole||p.assigned_team||p.assignedTeam||p.route_team||p.routeTeam||'').toLowerCase(); }
  function watchers(p){ const w=p.watchers||p.visibility||[]; return Array.isArray(w)?w.map(x=>String(x).toLowerCase()):[]; }
  function clientName(p){
    const c = p.client || p.client_data || {};
    return p.client_name || p.client || [c.firstName,c.lastName].filter(Boolean).join(' ') || [c.first_name,c.last_name].filter(Boolean).join(' ') || p.name || p.customer_name || '--';
  }
  function serviceName(p){ return p.service_title || p.serviceTitle || p.service || p.service_key || p.type || 'Pratica'; }
  function code(p){ return p.code || p.pratica_code || p.id || '--'; }
  function progressVal(p){ return pct(p.progress || p.workflow_progress || (String(p.status||'').toLowerCase().includes('complet')?100:25)); }
  function statusClass(s){ s=String(s||'').toLowerCase(); if(s.includes('complet')||s.includes('approv')||s.includes('attiva'))return'green'; if(s.includes('manc')||s.includes('integr')||s.includes('attesa'))return'orange'; if(s.includes('verif')||s.includes('lavor'))return'blue'; if(s.includes('respint')||s.includes('scad')||s.includes('non'))return'red'; return'gray'; }
  function pill(text, cls){ return `<span class="v26-pill ${cls||statusClass(text)}">${esc(text||'--')}</span>`; }
  function progress(n){ return `<div class="v26-progress"><i style="--p:${pct(n)}%"></i></div>`; }
  function rolePractices(role=state.session?.role){
    const email=String(state.session?.email||'').toLowerCase();
    const rows=[...(state.data.practices||[])];
    if(role==='admin') return rows;
    if(role==='agent') return rows.filter(p => String(p.agent_email||p.agentEmail||p.created_by||'').toLowerCase()===email || String(p.agent?.email||'').toLowerCase()===email);
    if(role==='bangla') return rows.filter(p => owner(p)==='bangla' || watchers(p).includes('bangla') || !owner(p));
    if(role==='italy') return rows.filter(p => owner(p)==='italy' || String(p.assigned_team||p.assignedTeam||'').toLowerCase()==='italy');
    if(role==='commercialista') return rows.filter(p => owner(p)==='commercialista' || watchers(p).includes('commercialista'));
    return rows;
  }
  function roleClients(role=state.session?.role){
    const email=String(state.session?.email||'').toLowerCase();
    let clients=[...(state.data.clients||[])];
    if(!clients.length){
      const map=new Map();
      rolePractices(role).forEach(p=>{ const key=(p.client_id||p.email||p.client_email||clientName(p)||code(p)); if(!map.has(key)) map.set(key,{ name:clientName(p), email:p.email||p.client_email||p.client?.email, phone:p.phone||p.client?.phone, cf:p.cf||p.client?.cf, lastPractice:code(p), created_by:p.created_by, agent_email:p.agent_email||p.agentEmail }); });
      clients=[...map.values()];
    }
    if(role==='agent') clients=clients.filter(c=>String(c.agent_email||c.created_by||c.owner_email||'').toLowerCase()===email || !c.created_by);
    if(role==='italy') { const names=new Set(rolePractices(role).map(p=>clientName(p))); clients=clients.filter(c=>names.has(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' '))); }
    return clients;
  }
  function kpis(role){ const ps=rolePractices(role); const all=state.data.practices||[]; const users=state.data.users||[]; const memberships=state.data.memberships||[]; const clients=roleClients(role); const credit=state.data.credit||{};
    if(role==='admin') return [
      ['Pratiche totali', all.length, 'backend live','fa-file-lines','green'], ['Agenti attivi', users.filter(u=>u.role==='agent'&&u.active!==false).length, '+ live','fa-users','orange'], ['Membri attivi', memberships.filter(m=>/attiv|approv/i.test(m.status||m.result||'')).length, '+ membership','fa-crown','purple'], ['Team Bangla in coda', all.filter(p=>owner(p)==='bangla'||!owner(p)).length, '+ workflow','fa-flag','blue'], ['Team Italy in coda', all.filter(p=>owner(p)==='italy').length, '+ workflow','fa-paper-plane','red'], ['Incassi mese', euro(all.reduce((s,p)=>s+Number(p.cost||p.amount||p.price||0),0)), '+ live','fa-coins','blue'] ];
    if(role==='agent') return [ ['Pratiche aperte', ps.filter(p=>!/complet/i.test(p.status||'')).length,'live','fa-file-lines','blue'], ['Pratiche complete', ps.filter(p=>/complet/i.test(p.status||'')).length,'live','fa-circle-check','green'], ['Membership attive', memberships.length,'live','fa-crown','orange'], ['Commissioni mese', euro(ps.reduce((s,p)=>s+Math.max(0,Number(p.cost||0)-Number(p.cafCost||p.caf_cost||0)),0)),'profitto','fa-percent','red'], ['Wallet disponibile', euro(credit.balance||0),'credito','fa-wallet','blue'], ['Clienti salvati', clients.length,'server','fa-users','green'] ];
    if(role==='bangla') return [ ['Nuove da agenti', ps.filter(p=>owner(p)==='bangla'||!owner(p)).length,'da controllare','fa-file-circle-plus','blue'], ['In verifica documenti', ps.filter(p=>/verif|doc/i.test(p.status||p.documentStatus||'')).length,'live','fa-magnifying-glass','red'], ['Documenti mancanti', ps.filter(p=>/manc|missing/i.test(p.documentStatus||p.status||'')).length,'richieste','fa-triangle-exclamation','orange'], ['Pronte per Italy', ps.filter(p=>progressVal(p)>=45 && owner(p)==='bangla').length,'autorizza','fa-paper-plane','blue'], ['Membership', memberships.length,'risultati','fa-crown','purple'], ['Clienti', clients.length,'database','fa-users','green'] ];
    if(role==='italy') return [ ['Assegnate', ps.length,'ricevute','fa-folder','blue'], ['In revisione', ps.filter(p=>/verif|revision|lavor/i.test(p.status||'')).length,'oggi','fa-clock','orange'], ['Da completare', ps.filter(p=>!/complet/i.test(p.status||'')).length,'workflow','fa-clipboard-check','green'], ['Membership esiti', memberships.length,'da gestire','fa-crown','purple'], ['Completate oggi', ps.filter(p=>/complet/i.test(p.status||'')).length,'done','fa-check-circle','green'], ['Documenti', ps.reduce((s,p)=>s+Number(p.files_count||0),0),'upload','fa-file-arrow-up','blue'] ];
    return [ ['Clienti attivi', clients.length,'server','fa-users','green'], ['Pratiche fiscali', ps.length,'studio','fa-folder','orange'], ['Fatture emesse', 0,'reale','fa-file-invoice','green'], ['Scadenze oggi', 0,'reale','fa-calendar-days','red'], ['Incassi mese', euro(ps.reduce((s,p)=>s+Number(p.cost||0),0)),'live','fa-coins','blue'], ['Membership business', memberships.length,'aziende','fa-crown','orange'] ];
  }
  function navFor(role){
    const common=[['dashboard','Dashboard','fa-house']];
    const map={
      admin:[...common,['users','Utenti & Ruoli','fa-user-shield'],['agents','Agenti','fa-users'],['bangla','Team Bangla','fa-circle'],['italy','Team Italy','fa-circle'],['commercialista','Commercialista','fa-building-columns'],['membership','Membership','fa-crown'],['practices','Pratiche','fa-file-lines'],['credit','Credito agenti','fa-coins'],['documents','Documenti','fa-folder'],['tickets','Tickets','fa-headset'],['reports','Report','fa-chart-line'],['settings','Impostazioni','fa-gear']],
      agent:[...common,['create','Crea pratica','fa-file-circle-plus'],['clients','I miei clienti','fa-users'],['practices','I miei ordini','fa-box'],['membership','Membership','fa-crown'],['wallet','Wallet','fa-wallet'],['commissioni','Commissioni','fa-chart-column'],['documents','Documenti','fa-folder'],['tickets','Supporto','fa-headset']],
      bangla:[...common,['agent-inbox','Nuove da Agenti','fa-file-import'],['verify','Verifica documenti','fa-circle-check'],['clients','Clienti','fa-users'],['practices','Pratiche','fa-file-lines'],['transfers','Trasferimenti','fa-paper-plane'],['membership','Membership','fa-crown'],['commercialista-lead','Commercialista lead','fa-building-columns'],['daily','Report giornaliero','fa-calendar-check'],['tickets','Ticket Admin','fa-comments']],
      italy:[...common,['assigned','Pratiche assegnate','fa-folder-open'],['review730','730 Review','fa-id-card'],['complete','Da completare','fa-clipboard-check'],['documents','Documenti','fa-file-arrow-up'],['membership','Membership esiti','fa-crown'],['tickets','Ticket','fa-headset'],['profile','Profilo & Salary','fa-user']],
      commercialista:[...common,['clients','Clienti','fa-users'],['company-new','Nuovo cliente / ditta','fa-plus'],['sales','Vendite e incassi','fa-chart-line'],['practices','Pratiche','fa-folder'],['invoices','Fatturazione','fa-file-invoice'],['f24','F24 e contributi','fa-building-columns'],['employees','Dipendenti','fa-users-gear'],['documents','Documenti','fa-folder-open'],['messages','Comunicazioni','fa-envelope'],['deadlines','Scadenze','fa-calendar'],['packages','Piani e pagamenti','fa-layer-group'],['reports','Report','fa-chart-pie']]
    };
    return map[role]||common;
  }
  function hero(){
    const role=state.session?.role||'admin';
    const data={
      admin:['Centro operativo totale','Gestisci pratiche, team, vendite, commissioni e tutte le operazioni in un unico pannello sicuro.'],
      agent:['Il tuo lavoro, più valore per le persone','Crea nuove pratiche, gestisci clienti, segui membership, credito e risultati in tempo reale.'],
      bangla:['Team Bangla Control Center','Ricevi ordini dagli agenti, verifica documenti, gestisci clienti, autorizza e trasferisci a Team Italy.'],
      italy:['Team Italy','Completa, verifica e finalizza le pratiche ricevute da Team Bangla, con qualità e ricevute.'],
      commercialista:['Area Commercialista','Gestisci clienti, ditte, pratiche fiscali, contabilità, documenti e adempimenti.']
    }[role]||['CAF CAE Pro','Gestionale operativo'];
    const actions = role==='admin' ? `${btn('Crea pratica','orange','data-page="create"')} ${btn('Nuovo utente','blue','data-page="users"')} ${btn('Nuova membership','purple','data-page="membership"')}` : role==='agent' ? `${btn('Nuova pratica','orange','data-page="create"')} ${btn('Nuova membership','blue','data-page="membership"')}` : role==='bangla' ? `${btn('Nuova pratica','orange','data-page="create"')} ${btn('Nuovo cliente','blue','data-page="clients"')} ${btn('Report giornaliero','green','data-page="daily"')}` : role==='italy' ? `${btn('Apri pratica','orange','data-page="assigned"')} ${btn('Carica ricevuta','blue','data-page="documents"')} ${btn('Ritorna a Bangla','light','data-page="assigned"')}` : `${btn('Nuovo cliente / ditta','blue','data-page="company-new"')} ${btn('Nuova pratica fiscale','orange','data-page="practices"')} ${btn('F24 e contributi','green','data-page="f24"')}`;
    return `<section class="v26-hero"><div><span class="v26-kicker"><i class="fa-solid fa-circle"></i> CAF CAE Pro</span><h1>${esc(data[0])}</h1><p>${esc(data[1])}</p></div><div class="v26-hero-actions">${actions}</div></section>`;
  }
  function btn(label, cls='light', attrs=''){ return `<button class="v26-btn ${cls}" ${attrs}>${label.includes('<')?label:esc(label)}</button>`; }
  function metricCard([label,value,sub,icon,cls]){ return `<article class="v26-card v26-metric ${cls||''}"><div class="v26-ico"><i class="fa-solid ${icon||'fa-chart-line'}"></i></div><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(sub)}</small></article>`; }
  function tableRows(rows, limit=8){
    if(!rows.length) return `<tr><td colspan="8"><div class="v26-empty">Nessun dato reale trovato. Crea una pratica o sincronizza dal backend.</div></td></tr>`;
    return rows.slice(0,limit).map(p=>`<tr data-filter="${esc((code(p)+' '+clientName(p)+' '+serviceName(p)).toLowerCase())}"><td><b>${esc(code(p))}</b></td><td>${esc(clientName(p))}</td><td>${esc(serviceName(p))}</td><td>${esc(roleName(owner(p)||'bangla'))}</td><td>${pill(p.status||p.workflow_status||'Nuova')}</td><td>${esc(p.document_status||p.documentStatus||'--')}</td><td>${progress(progressVal(p))}</td><td>${btn('Apri','light',`data-detail="${esc(p.id||p.code)}"`)}</td></tr>`).join('');
  }
  function practicesTable(title, subtitle, rows, filter=true){
    return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>${esc(title)}</h2><p>${esc(subtitle)}</p></div>${filter?`<div class="v26-search" style="max-width:310px"><i class="fa-solid fa-search"></i><input data-local-search placeholder="Cerca cliente, pratica..."></div>`:''}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Codice</th><th>Cliente</th><th>Servizio</th><th>Team</th><th>Stato</th><th>Docs</th><th>Avanzamento</th><th>Azioni</th></tr></thead><tbody>${tableRows(rows,20)}</tbody></table></div></section>`;
  }
  function membershipPanel(){ const rows=state.data.memberships||[]; const active=rows.filter(m=>/attiv|approv|idoneo/i.test(m.status||m.result||'')).length; const pending=rows.filter(m=>/attesa|revision/i.test(m.status||m.result||'')).length; const bad=rows.filter(m=>/scad|respint|non/i.test(m.status||m.result||'')).length; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Risultati Membership</h2><p>Stato reale delle membership salvate nel backend.</p></div>${btn('Vedi dettagli','light','data-page="membership"')}</div><div style="display:flex;gap:24px;align-items:center;flex-wrap:wrap"><div class="v26-donut"><span>${rows.length}<small>Totali</small></span></div><div style="display:grid;gap:10px;min-width:210px"><b>Attive: ${active}</b><b>In revisione: ${pending}</b><b>Non idonee/scadute: ${bad}</b><b>Da rinnovare: ${rows.filter(m=>/rinnov/i.test(m.status||'')).length}</b></div></div></section>`; }
  function workflowPanel(){ const all=state.data.practices||[]; const inserted=all.length, bangla=all.filter(p=>owner(p)==='bangla'||!owner(p)).length, italy=all.filter(p=>owner(p)==='italy').length, done=all.filter(p=>/complet/i.test(p.status||'')).length; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Workflow pratiche</h2><p>Agent → Team Bangla → Team Italy → completata.</p></div></div><div class="v26-flow"><div class="step"><span class="num">1</span><div><b>${inserted}</b><p>Inserite</p></div></div><div class="step"><span class="num">2</span><div><b>${bangla}</b><p>Team Bangla</p></div></div><div class="step"><span class="num">3</span><div><b>${italy}</b><p>Team Italy</p></div></div><div class="step"><span class="num">4</span><div><b>${done}</b><p>Completate</p></div></div></div><div class="v26-mini-bars" style="margin-top:16px">${[22,35,28,50,45,60,40,72,58,80,65,90].map(h=>`<i style="--h:${h}%"></i>`).join('')}</div></section>`; }
  function quickActions(role){ const items = role==='admin' ? [['Nuova pratica','orange','create'],['Nuovo agente','blue','agents'],['Nuova membership','purple','membership'],['Assegna team','light','users']] : role==='agent' ? [['Nuova pratica','orange','create'],['Nuova membership','blue','membership'],['Nuovo cliente','light','clients'],['Carica documenti','light','documents'],['Calcola profitto','light','wallet'],['Verifica stato','light','practices']] : role==='bangla' ? [['Nuova pratica','orange','create'],['Nuovo cliente','blue','clients'],['Carica documenti','light','documents'],['Invia a Italy','green','transfers']] : role==='italy' ? [['Carica documenti','orange','documents'],['Nuova integrazione','blue','assigned'],['Ritorna a Bangla','light','assigned'],['Nuova nota','light','tickets']] : [['Nuovo cliente / ditta','blue','company-new'],['Nuova pratica fiscale','orange','practices'],['Emetti fattura','purple','invoices'],['F24 e contributi','green','f24']]; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Azioni rapide</h2><p>Operazioni principali</p></div></div><div class="v26-actions ${items.length>4?'two':''}">${items.map(([l,c,p])=>btn(`<i class="fa-solid fa-plus"></i> ${esc(l)}`,c,`data-page="${p}"`)).join('')}</div></section>`; }
  function activityPanel(){ const rows=(state.data.notifications||[]).slice(0,8); return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Attività recenti</h2><p>Movimenti e notifiche reali</p></div>${btn('Vedi tutte','light','data-page="notifications"')}</div><div class="v26-activity">${rows.map(n=>`<div class="v26-activity-item"><span class="dot"></span><div><b>${esc(n.title||n.type||'Notifica')}</b><span>${esc(n.message||n.description||'')}</span></div><small>${esc(fmt(n.created_at||n.createdAt))}</small></div>`).join('')||'<div class="v26-empty">Nessuna notifica reale.</div>'}</div></section>`; }
  function dashboard(){ const role=state.session?.role||'admin'; const ps=rolePractices(role); return `${hero()}<section class="v26-grid v26-metrics">${kpis(role).map(metricCard).join('')}</section>${role==='bangla'?banglaDashboard(ps):role==='italy'?italyDashboard(ps):role==='commercialista'?commercialistaDashboard(ps):role==='agent'?agentDashboard(ps):adminDashboard(ps)}`; }
  function adminDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${membershipPanel()}${practicesTable('Pratiche recenti','Ultime pratiche reali inserite nel sistema', ps)}</div><aside class="v26-grid">${quickActions('admin')}${activityPanel()}</aside></div>`; }
  function agentDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${membershipTable()}<div class="v26-layout wide"><div>${clientsCard()}</div><div>${statusBars(ps)}</div></div></div><aside class="v26-grid">${quickActions('agent')}${activityPanel()}</aside></div>`; }
  function banglaDashboard(ps){ return `<div class="v26-grid"><section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Flusso pratiche</h2><p>Primo controllo operativo prima di Team Italy.</p></div></div><div class="v26-flow"><div class="step"><span class="num">1</span><div><b>${ps.filter(p=>owner(p)==='bangla'||!owner(p)).length}</b><p>Da controllare</p></div></div><div class="step"><span class="num">2</span><div><b>${ps.filter(p=>/manc/i.test(p.documentStatus||p.status||'')).length}</b><p>Documenti mancanti</p></div></div><div class="step"><span class="num">3</span><div><b>${ps.filter(p=>progressVal(p)>=45).length}</b><p>Autorizzate</p></div></div><div class="step"><span class="num">4</span><div><b>${(state.data.practices||[]).filter(p=>owner(p)==='italy').length}</b><p>Trasferite a Italy</p></div></div></div></section><div class="v26-layout"><div>${practicesTable('Pratiche recenti','Elenco pratiche assegnate a Team Bangla',ps)}</div><aside class="v26-grid">${quickActions('bangla')}${membershipPanel()}${activityPanel()}</aside></div></div>`; }
  function italyDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${practicesTable('Pratiche assegnate a Team Italy','Qui trovi solo le pratiche autorizzate e trasferite da Team Bangla.',ps)}${workflowPanel()}</div><aside class="v26-grid">${membershipPanel()}${quickActions('italy')}${deadlinesCard(ps)}</aside></div>`; }
  function commercialistaDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid"><section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Nuovo cliente / nuova ditta</h2><p>Inserisci dati cliente o azienda con piano e documenti.</p></div>${btn('Salva e continua più tardi','light')}</div>${companyMiniForm()}</section><div class="v26-layout wide"><div>${deadlinesCard(ps)}</div><div>${documentsMissingCard()}</div></div>${practicesTable('Pratiche fiscali recenti','Pratiche reali collegate allo studio commercialista',ps)}</div><aside class="v26-grid">${quickActions('commercialista')}${packagesCard()}</aside></div>`; }
  function membershipTable(){ const rows=state.data.memberships||[]; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Risultati membership</h2><p>Controlla stato e risultati membership dei tuoi clienti.</p></div>${btn('Vedi tutte','light','data-page="membership"')}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Cliente</th><th>Tipo</th><th>Stato</th><th>Risultato</th><th>Scadenza</th><th>Team</th></tr></thead><tbody>${rows.slice(0,8).map(m=>`<tr><td>${esc(m.client_name||m.name||'--')}</td><td>${esc(m.type||m.membership_type||'Membership')}</td><td>${pill(m.status||'--')}</td><td>${pill(m.result||'--')}</td><td>${esc(fmt(m.expires_at||m.deadline))}</td><td>${esc(roleName(m.team_role||m.team))}</td></tr>`).join('')||'<tr><td colspan="6"><div class="v26-empty">Nessuna membership reale.</div></td></tr>'}</tbody></table></div></section>`; }
  function clientsCard(){ const rows=roleClients(); return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Clienti recenti</h2><p>Database clienti salvato sul server.</p></div>${btn('Vedi tutti','light','data-page="clients"')}</div>${rows.slice(0,5).map(c=>`<div class="v26-staff"><span class="v26-avatar">${esc((c.name||c.full_name||'C').slice(0,2).toUpperCase())}</span><div><b>${esc(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||'Cliente')}</b><span>${esc(c.cf||c.phone||c.email||'')}</span></div></div>`).join('')||'<div class="v26-empty">Nessun cliente reale.</div>'}</section>`; }
  function statusBars(ps){ const rows=[['Nuove',ps.filter(p=>/nuov/i.test(p.status||'')).length,20],['In lavorazione',ps.filter(p=>/lavor/i.test(p.status||'')).length,45],['In verifica',ps.filter(p=>/verif/i.test(p.status||'')).length,30],['Complete',ps.filter(p=>/complet/i.test(p.status||'')).length,85],['Sospese',ps.filter(p=>/sosp/i.test(p.status||'')).length,15]]; return `<section class="v26-card v26-section"><h2>Stato pratiche</h2><div style="display:grid;gap:15px;margin-top:15px">${rows.map(r=>`<div style="display:grid;grid-template-columns:110px 36px 1fr;gap:12px;align-items:center"><b>${r[0]}</b><span>${r[1]}</span>${progress(r[2])}</div>`).join('')}</div></section>`; }
  function deadlinesCard(ps){ return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Prossime scadenze</h2><p>Scadenze reali dalle pratiche.</p></div></div>${ps.slice(0,6).map(p=>`<div class="v26-staff"><span class="v26-avatar" style="background:#fee2e2;color:#b91c1c">${esc(String((p.deadline||p.scadenza||'--')).slice(8,10)||'--')}</span><div><b>${esc(code(p))}</b><span>${esc(clientName(p)+' · '+serviceName(p))}</span></div></div>`).join('')||'<div class="v26-empty">Nessuna scadenza reale.</div>'}</section>`; }
  function documentsMissingCard(){ return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Documenti mancanti</h2><p>Da caricare o richiedere al cliente.</p></div></div><div class="v26-empty">Seleziona una pratica per vedere i documenti mancanti reali.</div></section>`; }
  function packagesCard(){ const packs=state.data.packages||[]; return `<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Piani Commercialista</h2><p>Pacchetti reali/configurabili.</p></div></div>${packs.map(p=>`<div class="v26-staff"><span class="v26-avatar"><i class="fa-solid fa-layer-group"></i></span><div><b>${esc(p.name||p.title)}</b><span>${euro(p.monthly_price||p.price||0)} / mese</span></div></div>`).join('')||'<div class="v26-empty">Nessun piano salvato.</div>'}</section>`; }
  function companyMiniForm(){ return `<form class="v26-form"><label>Nome<input placeholder="Mario"></label><label>Cognome<input placeholder="Bianchi"></label><label>Email<input placeholder="cliente@email.it"></label><label>Codice fiscale<input placeholder="BNCMRA..."></label><label>Telefono<input placeholder="+39..."></label><label>Tipo cliente<select><option>Persona fisica</option><option>Ditta individuale</option><option>Società</option></select></label><label class="wide">Indirizzo<input placeholder="Via Roma 123"></label><button class="v26-btn orange" type="button" data-page="company-new">Avanti</button></form>`; }
  function pageContent(){ const role=state.session?.role||'admin'; const ps=rolePractices(role); if(state.page==='dashboard') return dashboard(); if(state.page==='create'||state.page==='company-new') return createPage(role); if(state.page==='clients'||state.page==='agents'||state.page==='users') return clientsPage(role); if(state.page==='documents') return documentsPage(ps); if(state.page==='membership') return membershipPage(); if(state.page==='credit'||state.page==='wallet') return creditPage(); if(state.page==='daily') return dailyPage(); if(state.page==='tickets') return ticketsPage(); if(['practices','assigned','agent-inbox','verify','transfers','review730','complete'].includes(state.page)) return `${hero()}${practicesTable(state.page==='assigned'?'Pratiche assegnate':'Pratiche','Dati reali dal backend',ps)}`; if(state.page==='detail') return detailPage(state.detail); return `${hero()}${practicesTable('Dati reali','Modulo in costruzione collegato al backend',ps)}`; }
  function createPage(role){ const services=[['Modello 730','730','35','6'],['ISEE Ordinario','ISEE','25','4'],['NASpI','NASPI','30','5'],['Assegno Unico','AU','25','4'],['Permesso di Soggiorno','PDS','40','8'],['Ricongiungimento Familiare','RICONG','60','8'],['Cittadinanza Italiana','CITT','80','10'],['Apertura Partita IVA','PIVA','50','6']]; return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Crea nuova pratica</h2><p>Salva cliente, pratica e workflow direttamente nel backend. Agent → Team Bangla; Admin/Bangla possono scegliere team.</p></div></div><div class="v26-service-grid" id="v26Services">${services.map((s,i)=>`<button type="button" class="v26-service ${i===0?'active':''}" data-service="${esc(s[1])}" data-title="${esc(s[0])}" data-price="${s[2]}" data-caf="${s[3]}"><b>${esc(s[0])}</b><span>Prezzo cliente €${s[2]} · costo CAF €${s[3]}</span></button>`).join('')}</div><form class="v26-form" id="v26CreateForm" style="margin-top:18px"><input type="hidden" name="service" value="730"><input type="hidden" name="serviceTitle" value="Modello 730"><input type="hidden" name="price" value="35"><input type="hidden" name="cafCost" value="6"><label>Nome<input name="firstName" required></label><label>Cognome<input name="lastName" required></label><label>Email<input name="email"></label><label>Telefono<input name="phone"></label><label>Codice fiscale<input name="cf"></label><label>Team destinazione<select name="team"><option value="bangla">Team Bangla</option>${role==='admin'||role==='bangla'?'<option value="commercialista">Commercialista</option><option value="italy">Team Italy (solo admin/autorizzato)</option>':''}</select></label><label>Prezzo cliente<input name="clientPaid" type="number" value="35"></label><label>Costo CAF CAE<input name="cafCostInput" type="number" value="6"></label><label>Profitto agente<input name="profit" readonly value="29"></label><label class="wide">Note pratica<textarea name="note"></textarea></label><button class="v26-btn orange" type="submit"><i class="fa-solid fa-paper-plane"></i> Salva pratica nel backend</button></form></section>`; }
  function clientsPage(role){ const rows=roleClients(role); return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Clienti</h2><p>Archivio clienti server con auto-fill futuro.</p></div>${btn('Nuovo cliente','orange','data-page="create"')}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Nome</th><th>CF</th><th>Telefono</th><th>Email</th><th>Ultima pratica</th><th>Azione</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||'--')}</td><td>${esc(c.cf||'--')}</td><td>${esc(c.phone||'--')}</td><td>${esc(c.email||'--')}</td><td>${esc(c.lastPractice||'--')}</td><td>${btn('Apri','light')}</td></tr>`).join('')||'<tr><td colspan="6"><div class="v26-empty">Nessun cliente reale.</div></td></tr>'}</tbody></table></div></section>`; }
  function documentsPage(ps){ return `${hero()}${practicesTable('Documenti e allegati','Apri una pratica per caricare, vedere anteprima e scaricare documenti.', ps)}`; }
  function membershipPage(){ return `${hero()}${membershipPanel()}${membershipTable()}`; }
  function creditPage(){ const cr=state.data.credit||{}; const req=[]; return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Credito / Wallet</h2><p>Saldo, richieste e storico movimenti.</p></div>${state.session?.role==='agent'?btn('Richiedi credito','orange','id="v26CreditReq"'):''}</div><div class="v26-metrics v26-grid"><article class="v26-card v26-metric green"><div class="v26-ico"><i class="fa-solid fa-wallet"></i></div><span>Saldo disponibile</span><strong>${euro(cr.balance||0)}</strong><small>backend</small></article><article class="v26-card v26-metric orange"><div class="v26-ico"><i class="fa-solid fa-clock"></i></div><span>Movimenti</span><strong>${(cr.ledger||[]).length}</strong><small>storico</small></article></div></section>`; }
  function dailyPage(){ return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Report giornaliero team</h2><p>Invia il lavoro svolto ad Admin per monitoraggio.</p></div></div><form class="v26-form" id="v26DailyForm"><label>Pratiche controllate<input name="checked" type="number"></label><label>Completate<input name="done" type="number"></label><label>Documenti richiesti<input name="missing" type="number"></label><label class="wide">Note<textarea name="notes" required></textarea></label><button class="v26-btn green" type="submit">Invia report</button></form></section>`; }
  function ticketsPage(){ return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Ticket</h2><p>Problemi, richieste admin e comunicazioni operative.</p></div></div><form class="v26-form" id="v26TicketForm"><label>Oggetto<input name="subject" required></label><label>Pratica<input name="practice_code"></label><label>Destinatario<select name="target_role"><option value="admin">Admin</option><option value="bangla">Team Bangla</option><option value="italy">Team Italy</option><option value="commercialista">Commercialista</option></select></label><label class="wide">Messaggio<textarea name="message" required></textarea></label><button class="v26-btn orange" type="submit">Invia ticket</button></form></section>`; }
  async function filesFor(id){ try { return (await api('/api/practices/'+encodeURIComponent(id)+'/files')).files||[]; } catch { return []; } }
  function detailPage(id){ const p=(state.data.practices||[]).find(x=>String(x.id)===String(id)||String(x.code)===String(id)); if(!p) return `${hero()}<div class="v26-empty">Pratica non trovata</div>`; const hist=[...(p.workflow_events||p.workflowEvents||[]),...(p.team_history||p.teamHistory||[])].slice(0,8); return `${hero()}<section class="v26-card v26-section"><div class="v26-section-head"><div><h2>${esc(code(p))}</h2><p>${esc(clientName(p))} · ${esc(serviceName(p))}</p></div><div class="v26-hero-actions">${owner(p)==='bangla'||state.session?.role==='admin'?btn('Autorizza Team Italy','green',`data-authorize="${esc(p.id)}"`):''}${btn('Carica documenti','orange',`data-upload="${esc(p.id)}"`)}${btn('Carica ricevuta','blue',`data-upload-receipt="${esc(p.id)}"`)}</div></div><div class="v26-detail-grid"><div class="v26-card v26-section"><h3>Info cliente</h3><p><b>${esc(clientName(p))}</b></p><p>Email: ${esc(p.email||p.client?.email||'--')}</p><p>Tel: ${esc(p.phone||p.client?.phone||'--')}</p><p>CF: ${esc(p.cf||p.client?.cf||'--')}</p></div><div class="v26-card v26-section"><h3>Pratica</h3><p>Servizio: <b>${esc(serviceName(p))}</b></p><p>Owner: <b>${esc(roleName(owner(p)))}</b></p><p>Stato: ${pill(p.status||'Nuova')}</p><p>Documenti: ${esc(p.document_status||p.documentStatus||'--')}</p>${progress(progressVal(p))}<div id="v26Files" class="v26-doc-list" style="margin-top:18px"><div class="v26-empty">Caricamento allegati...</div></div></div><div class="v26-card v26-section"><h3>Timeline</h3><div class="v26-activity">${hist.map(h=>`<div class="v26-activity-item"><span class="dot"></span><div><b>${esc(h.action||h.message||'Update')}</b><span>${esc(h.by||h.actor_name||'Sistema')}</span></div><small>${esc(fmt(h.date||h.created_at))}</small></div>`).join('')||'<div class="v26-empty">Nessuna timeline</div>'}</div></div></div></section>`; }
  function shell(){ const sess=state.session||readSession()||{}; const role=sess.role||'admin'; const nav=navFor(role); return `<aside class="v26-sidebar"><div class="v26-brand"><span class="v26-logo-mark">C</span><div><strong>CAF CAE <span>Pro</span></strong><small>Servizi. Persone. Risultati.</small></div></div><div class="v26-user-mini"><span class="v26-avatar">${esc((sess.name||sess.email||role).slice(0,2).toUpperCase())}</span><div><b>${esc(sess.name||sess.email||'Utente')}</b><span>${esc(roleLabel(role))}</span></div></div><nav class="v26-nav"><div class="v26-nav-title">Menu operativo</div>${nav.map(([p,l,i])=>`<button data-page="${p}" class="${state.page===p?'active':''}"><i class="fa-solid ${i}"></i>${esc(l)}${p==='tickets'?'<span class="v26-badge">!</span>':''}</button>`).join('')}</nav><div class="v26-sidebar-footer"><b>CAF CAE Pro v26</b><br>UI nuova completa · backend live</div></aside><main class="v26-main"><header class="v26-topbar"><button class="v26-menu-toggle" id="v26Menu"><i class="fa-solid fa-bars"></i></button><div class="v26-titlebox"><b>${esc(titleForPage())}</b><p>${esc(subtitleForRole(role))}</p></div><div class="v26-search"><i class="fa-solid fa-search"></i><input id="v26GlobalSearch" value="${esc(state.search)}" placeholder="Cerca pratiche, utenti, documenti, clienti..."></div><div class="v26-top-actions"><button class="v26-icon"><i class="fa-regular fa-bell"></i><em>${state.data.notifications?.length||0}</em></button><button class="v26-icon"><i class="fa-regular fa-message"></i></button><button class="v26-icon"><i class="fa-regular fa-circle-question"></i></button><div class="v26-profile"><span class="v26-avatar">${esc((sess.name||role).slice(0,1).toUpperCase())}</span><div><b>${esc(sess.name||sess.email||'Utente')}</b><span>${esc(roleLabel(role))}</span></div></div></div></header><div class="v26-content" id="v26Content">${pageContent()}</div></main><input id="v26FileInput" type="file" multiple class="v26-hide">`; }
  function titleForPage(){ const p=state.page; const m={dashboard:'Dashboard',create:'Crea pratica',clients:'Clienti',practices:'Pratiche',documents:'Documenti',membership:'Membership Center',credit:'Credito agenti',wallet:'Wallet',tickets:'Ticket',daily:'Report giornaliero',detail:'Dettaglio pratica'}; return m[p]||p.replace(/-/g,' ').replace(/^./,c=>c.toUpperCase()); }
  function subtitleForRole(role){ return ({admin:'Panoramica generale del sistema CAF CAE Pro',agent:'Panoramica attività, clienti, pratiche e risultati',bangla:'Gestisci clienti, documenti e pratiche per Team Italy',italy:'Panoramica operativa del Team Italy',commercialista:'Gestisci il tuo studio professionale in modo semplice e sicuro'}[role]||'CAF CAE Pro'); }
  function render(){ const shellEl=$('#appShell'); if(!token() || !readSession()) return showLogin(); if(!shellEl || shellEl.classList.contains('hidden')) return false; const loginRoot=document.getElementById('caeV29LoginRoot'); if(loginRoot) loginRoot.remove(); document.body.classList.remove('cae-v29-login-active'); document.body.classList.add('cae-v26-active'); shellEl.classList.add('cae-v26-mounted'); let app=$('#caeV26App'); if(!app){ app=document.createElement('div'); app.id='caeV26App'; shellEl.appendChild(app); } app.innerHTML=shell(); if(state.detail) setTimeout(loadFilesIntoDetail,50); return true; }
  async function mount(){ if(state.mounted) return; const ok=await loadSession(); if(!ok){ showLogin(); return; } await loadData(); state.mounted=true; render(); }
  async function refresh(){ await loadSession(); await loadData(); render(); }
  async function loadFilesIntoDetail(){ const box=$('#v26Files'); if(!box || !state.detail) return; const files=await filesFor(state.detail); box.innerHTML = files.map(f=>`<div class="v26-doc"><i class="fa-solid fa-file-pdf"></i><div><b>${esc(f.file_name||f.name||'Documento')}</b><small>${esc(f.category||'Allegato')} · ${esc(f.uploaded_by_name||'')}</small></div><a class="v26-btn light" target="_blank" href="${API()}/api/files/${encodeURIComponent(f.id)}/preview?token=${encodeURIComponent(token())}">Anteprima</a><a class="v26-btn green" target="_blank" href="${API()}/api/files/${encodeURIComponent(f.id)}/download?token=${encodeURIComponent(token())}">Scarica</a></div>`).join('') || '<div class="v26-empty">Nessun allegato caricato. Usa “Carica documenti”.</div>'; }
  async function submitCreate(form){ const fd=new FormData(form); const service=fd.get('serviceTitle')||fd.get('service')||'Pratica'; const first=fd.get('firstName'), last=fd.get('lastName'); const team=fd.get('team')||'bangla'; const payload={ code:`CAF-${String(fd.get('service')||'PRATICA').toUpperCase()}-${new Date().getFullYear()}-${String((state.data.practices.length||0)+1).padStart(4,'0')}`, serviceTitle:service, service_key:fd.get('service'), service:service, current_owner:team, currentOwner:team, assigned_team:team, route_team:team, status:'Nuova', documentStatus:'Documenti mancanti', progress:15, cost:Number(fd.get('clientPaid')||fd.get('price')||0), cafCost:Number(fd.get('cafCostInput')||fd.get('cafCost')||0), client:{firstName:first,lastName:last,email:fd.get('email'),phone:fd.get('phone'),cf:fd.get('cf')}, client_name:[first,last].filter(Boolean).join(' '), email:fd.get('email'), phone:fd.get('phone'), cf:fd.get('cf'), note:fd.get('note') };
    await api('/api/v22/practices',{method:'POST',json:{practice:payload}}); await refresh(); state.page='dashboard'; render(); toast('Pratica salvata nel backend.'); }
  async function uploadFiles(id,isReceipt=false){ const inp=$('#v26FileInput'); inp.value=''; inp.onchange=async()=>{ if(!inp.files.length) return; const fd=new FormData(); [...inp.files].forEach(f=>fd.append('files',f)); fd.append('is_receipt', isReceipt?'true':'false'); fd.append('category', isReceipt?'Ricevuta':'Documento'); await api('/api/practices/'+encodeURIComponent(id)+'/files/upload',{method:'POST',body:fd}); toast('Documento caricato.'); await loadFilesIntoDetail(); await loadData(); render(); }; inp.click(); }
  async function authorize(id){ await api('/api/v22/practices/'+encodeURIComponent(id)+'/authorize',{method:'POST',json:{target:'italy'}}); toast('Pratica autorizzata e inviata a Team Italy.'); await refresh(); }
  async function dailyReport(form){ const fd=new FormData(form); await api('/api/v22/team/daily-report',{method:'POST',json:{team_role:state.session.role, checked:Number(fd.get('checked')||0), done:Number(fd.get('done')||0), missing:Number(fd.get('missing')||0), notes:fd.get('notes')}}); toast('Report inviato ad Admin.'); }
  async function ticket(form){ const fd=new FormData(form); await api('/api/v22/tickets',{method:'POST',json:{subject:fd.get('subject'), practice_code:fd.get('practice_code'), target_role:fd.get('target_role'), message:fd.get('message')}}); toast('Ticket inviato.'); }
  function toast(msg){ const t=$('#toast'); if(t){ t.textContent=msg; t.className='toast'; setTimeout(()=>t.classList.add('hidden'),2600); } else alert(msg); }
  document.addEventListener('click', e=>{
    const page=e.target.closest('[data-page]'); if(page){ e.preventDefault(); state.page=page.dataset.page; state.detail=null; render(); return; }
    const det=e.target.closest('[data-detail]'); if(det){ e.preventDefault(); state.page='detail'; state.detail=det.dataset.detail; render(); return; }
    const up=e.target.closest('[data-upload]'); if(up){ e.preventDefault(); uploadFiles(up.dataset.upload,false); return; }
    const rec=e.target.closest('[data-upload-receipt]'); if(rec){ e.preventDefault(); uploadFiles(rec.dataset.uploadReceipt,true); return; }
    const au=e.target.closest('[data-authorize]'); if(au){ e.preventDefault(); authorize(au.dataset.authorize); return; }
    if(e.target.closest('#v26Menu')) document.body.classList.toggle('v26-open');
    const svc=e.target.closest('.v26-service'); if(svc){ $$('.v26-service').forEach(x=>x.classList.remove('active')); svc.classList.add('active'); const form=$('#v26CreateForm'); if(form){ form.service.value=svc.dataset.service; form.serviceTitle.value=svc.dataset.title; form.price.value=svc.dataset.price; form.cafCost.value=svc.dataset.caf; form.clientPaid.value=svc.dataset.price; form.cafCostInput.value=svc.dataset.caf; form.profit.value=Number(svc.dataset.price||0)-Number(svc.dataset.caf||0); } }
  });
  document.addEventListener('input', e=>{ if(e.target.name==='clientPaid'||e.target.name==='cafCostInput'){ const f=$('#v26CreateForm'); if(f) f.profit.value=Number(f.clientPaid.value||0)-Number(f.cafCostInput.value||0); } if(e.target.matches('[data-local-search]')){ const q=e.target.value.toLowerCase(); $$('[data-filter]').forEach(r=>r.style.display=r.dataset.filter.includes(q)?'':'none'); } if(e.target.id==='v26GlobalSearch'){ state.search=e.target.value; }});
  document.addEventListener('submit', e=>{ if(e.target.id==='v26CreateForm'){ e.preventDefault(); submitCreate(e.target).catch(err=>toast(err.message)); } if(e.target.id==='v26DailyForm'){ e.preventDefault(); dailyReport(e.target).catch(err=>toast(err.message)); } if(e.target.id==='v26TicketForm'){ e.preventDefault(); ticket(e.target).catch(err=>toast(err.message)); } });

  /* ===== v27 premium functional UI overrides: generated-image layout + all role options ===== */
  function v27MoneyFromPractice(p){ return Number(p.cost||p.amount||p.price||p.client_paid||0); }
  function v27Profit(p){ return Math.max(0, Number(p.cost||p.amount||p.price||0) - Number(p.cafCost||p.caf_cost||p.internal_cost||0)); }
  function v27Counts(){ const all=state.data.practices||[], ps=rolePractices(), mem=state.data.memberships||[], clients=roleClients(); return {all,ps,mem,clients}; }
  function v27Panel(title, subtitle, body, actions=''){ return `<section class="v26-card v26-section v27-panel"><div class="v26-section-head"><div><h2>${esc(title)}</h2><p>${esc(subtitle||'')}</p></div><div class="v27-actions-line">${actions}</div></div>${body}</section>`; }
  function v27SmallCard(icon,title,value,sub,cls='green'){ return `<article class="v26-card v27-small ${cls}"><div class="v26-ico"><i class="fa-solid ${icon}"></i></div><span>${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(sub||'')}</small></article>`; }
  function v27Tabs(items){ return `<div class="v27-tabs">${items.map(x=>`<button data-page="${esc(x[0])}" class="${state.page===x[0]?'active':''}"><i class="fa-solid ${esc(x[2]||'fa-circle')}"></i>${esc(x[1])}</button>`).join('')}</div>`; }
  function v27ClientRows(rows){ return rows.length ? rows.slice(0,50).map(c=>`<tr data-filter="${esc(((c.name||c.full_name||'')+' '+(c.cf||'')+' '+(c.phone||'')+' '+(c.email||'')).toLowerCase())}"><td><b>${esc(c.name||c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||'Cliente')}</b></td><td>${esc(c.cf||'--')}</td><td>${esc(c.phone||'--')}</td><td>${esc(c.email||'--')}</td><td>${esc(c.lastPractice||'--')}</td><td><button class="v26-btn light" data-page="create">Nuova pratica</button></td></tr>`).join('') : `<tr><td colspan="6"><div class="v26-empty">Nessun cliente reale ancora. Crea o importa un cliente: sarà salvato nel server e riusabile con auto-fill.</div></td></tr>`; }
  function v27PracticeRows(rows, opts={}){
    return rows.length ? rows.slice(0,60).map(p=>{ const canAuth=(state.session?.role==='bangla'||state.session?.role==='admin') && owner(p)!=='italy'; return `<tr data-filter="${esc((code(p)+' '+clientName(p)+' '+serviceName(p)).toLowerCase())}"><td><input type="checkbox"></td><td><b>${esc(code(p))}</b></td><td><div class="v27-client-dot"><span>${esc(clientName(p).slice(0,2).toUpperCase())}</span><b>${esc(clientName(p))}</b></div></td><td>${esc(serviceName(p))}</td><td>${esc(roleName(owner(p)||'bangla'))}</td><td>${pill(p.status||p.workflow_status||'Nuova')}</td><td>${esc(p.document_status||p.documentStatus||'--')}</td><td>${progress(progressVal(p))}<small>${progressVal(p)}%</small></td><td><div class="v27-row-actions"><button class="v26-btn light" data-detail="${esc(p.id||p.code)}">Apri</button>${canAuth?`<button class="v26-btn green" data-authorize="${esc(p.id)}">Invia Italy</button>`:''}<button class="v26-btn orange" data-upload="${esc(p.id)}">Upload</button></div></td></tr>`}).join('') : `<tr><td colspan="9"><div class="v26-empty">Nessuna pratica reale per questa sezione. Quando un agente crea una pratica apparirà qui dal backend.</div></td></tr>`;
  }
  function v27PracticeTable(title, subtitle, rows, actions=''){
    return v27Panel(title, subtitle, `<div class="v27-filterbar"><div class="v26-search"><i class="fa-solid fa-search"></i><input data-local-search placeholder="Cerca codice, cliente, servizio..."></div><button class="v26-btn light"><i class="fa-solid fa-sliders"></i> Filtri</button><button class="v26-btn light"><i class="fa-solid fa-download"></i> Esporta</button></div><div class="v26-table-wrap"><table class="v26-table v27-table"><thead><tr><th></th><th>Codice</th><th>Cliente</th><th>Servizio</th><th>Team</th><th>Stato</th><th>Docs</th><th>Avanzamento</th><th>Azioni</th></tr></thead><tbody>${v27PracticeRows(rows)}</tbody></table></div>`, actions);
  }
  function v27Hero(){
    const role=state.session?.role||'admin';
    const meta={admin:['Centro operativo totale','Gestisci pratiche, agenti, membership, team, credito e problemi in un unico sistema.','fa-shield-halved'],agent:['Area Agente CAF CAE','Crea pratiche, salva clienti, controlla credito, profitto, membership e documenti.','fa-user-tie'],bangla:['Team Bangla Control Center','Primo controllo: clienti, documenti, membership, autorizzazione e invio a Team Italy.','fa-flag'],italy:['Team Italy Practice Hub','Ricevi solo pratiche autorizzate, completa, carica ricevute e gestisci integrazioni.','fa-paper-plane'],commercialista:['Area Commercialista','Gestione ditte, pacchetti, fatture, F24, dipendenti, documenti e report clienti.','fa-building-columns']}[role] || ['CAF CAE Pro','Gestionale operativo','fa-gauge'];
    const actions = role==='italy' ? `${btn('<i class="fa-solid fa-folder-open"></i> Apri pratica','orange','data-page="assigned"')}${btn('<i class="fa-solid fa-upload"></i> Carica ricevuta','blue','data-page="documents"')}${btn('<i class="fa-solid fa-rotate-left"></i> Ritorna Bangla','light','data-page="assigned"')}` : role==='bangla' ? `${btn('<i class="fa-solid fa-plus"></i> Nuova pratica','orange','data-page="create"')}${btn('<i class="fa-solid fa-user-plus"></i> Nuovo cliente','blue','data-page="clients"')}${btn('<i class="fa-solid fa-paper-plane"></i> Invia Italy','green','data-page="transfers"')}${btn('<i class="fa-solid fa-calendar-check"></i> Report','light','data-page="daily"')}` : role==='agent' ? `${btn('<i class="fa-solid fa-plus"></i> Nuova pratica','orange','data-page="create"')}${btn('<i class="fa-solid fa-crown"></i> Nuova membership','blue','data-page="membership"')}${btn('<i class="fa-solid fa-wallet"></i> Richiedi credito','green','data-page="wallet"')}` : role==='commercialista' ? `${btn('<i class="fa-solid fa-plus"></i> Nuova ditta','orange','data-page="company-new"')}${btn('<i class="fa-solid fa-file-invoice"></i> Fattura','blue','data-page="invoices"')}${btn('<i class="fa-solid fa-folder-open"></i> Documenti','green','data-page="documents"')}` : `${btn('<i class="fa-solid fa-plus"></i> Crea pratica','orange','data-page="create"')}${btn('<i class="fa-solid fa-user-plus"></i> Nuovo agente','blue','data-page="agents"')}${btn('<i class="fa-solid fa-crown"></i> Membership','purple','data-page="membership"')}${btn('<i class="fa-solid fa-coins"></i> Credito','light','data-page="credit"')}`;
    return `<section class="v26-hero v27-hero"><div><span class="v26-kicker"><i class="fa-solid ${meta[2]}"></i> CAF CAE Pro v30</span><h1>${esc(meta[0])}</h1><p>${esc(meta[1])}</p></div><div class="v26-hero-actions">${actions}</div></section>`;
  }
  function hero(){ return v27Hero(); }
  function navFor(role){
    const common=[['dashboard','Dashboard','fa-house']];
    const map={
      admin:[...common,['create','Crea pratica','fa-plus'],['practices','Tutte pratiche','fa-folder-open'],['clients','Clienti','fa-users'],['agents','Agenti','fa-user-tie'],['users','Team & permessi','fa-user-shield'],['membership','Membership Center','fa-crown'],['credit','Credito agenti','fa-coins'],['documents','Documenti','fa-folder'],['tickets','Ticket & problemi','fa-headset'],['reports','Report live','fa-chart-line'],['settings','Servizi & prezzi','fa-gear']],
      agent:[...common,['create','Nuova pratica','fa-plus'],['clients','I miei clienti','fa-users'],['practices','I miei ordini','fa-box'],['membership','Membership','fa-crown'],['wallet','Wallet & credito','fa-wallet'],['commissioni','Profitto','fa-calculator'],['documents','Documenti','fa-folder'],['tickets','Supporto','fa-headset']],
      bangla:[...common,['agent-inbox','Inbox agenti','fa-inbox'],['create','Crea pratica','fa-plus'],['clients','Clienti','fa-users'],['verify','Verifica documenti','fa-circle-check'],['transfers','Invio a Italy','fa-paper-plane'],['membership','Membership risultati','fa-crown'],['documents','Documenti','fa-folder-open'],['daily','Report giornaliero','fa-calendar-check'],['tickets','Ticket Admin','fa-comments']],
      italy:[...common,['assigned','Pratiche assegnate','fa-folder-open'],['review730','730 Review','fa-id-card'],['complete','Da completare','fa-clipboard-check'],['documents','Upload ricevute','fa-file-arrow-up'],['membership','Membership esiti','fa-crown'],['tickets','Ticket','fa-headset'],['profile','Profilo & Salary','fa-user']],
      commercialista:[...common,['clients','Clienti / ditte','fa-users'],['company-new','Nuova ditta','fa-plus'],['practices','Pratiche fiscali','fa-folder'],['invoices','Fatturazione','fa-file-invoice'],['f24','F24 e contributi','fa-building-columns'],['employees','Dipendenti','fa-users-gear'],['documents','Documenti','fa-folder-open'],['packages','Piani e pacchetti','fa-layer-group'],['tickets','Ticket','fa-headset'],['reports','Report','fa-chart-pie']]
    }; return map[role]||common;
  }
  function dashboard(){ const role=state.session?.role||'admin'; const ps=rolePractices(role); return `${v27Hero()}<section class="v26-grid v26-metrics">${kpis(role).map(metricCard).join('')}</section>${role==='bangla'?banglaDashboard(ps):role==='italy'?italyDashboard(ps):role==='commercialista'?commercialistaDashboard(ps):role==='agent'?agentDashboard(ps):adminDashboard(ps)}`; }
  function adminDashboard(ps){ const c=v27Counts(); return `<div class="v26-layout"><div class="v26-grid">${workflowPanel()}${v27PracticeTable('Pratiche recenti','Solo dati reali dal backend/Supabase',ps)}${adminTeamMonitor()}</div><aside class="v26-grid">${quickActions('admin')}${adminCreditRequests()}${activityPanel()}</aside></div>`; }
  function agentDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${agentProfitPanel(ps)}${membershipTable()}<div class="v26-layout wide"><div>${clientsCard()}</div><div>${statusBars(ps)}</div></div></div><aside class="v26-grid">${quickActions('agent')}${agentCreditRequestBox()}${activityPanel()}</aside></div>`; }
  function banglaDashboard(ps){ return `<div class="v26-grid"><section class="v26-card v26-section"><div class="v26-section-head"><div><h2>Flusso operativo Team Bangla</h2><p>Agent crea → Team Bangla controlla → autorizza → Italy lavora.</p></div></div><div class="v26-flow"><div class="step"><span class="num">1</span><div><b>${ps.filter(p=>owner(p)==='bangla'||!owner(p)).length}</b><p>Da controllare</p></div></div><div class="step"><span class="num">2</span><div><b>${ps.filter(p=>/manc|doc/i.test(p.documentStatus||p.status||'')).length}</b><p>Documenti mancanti</p></div></div><div class="step"><span class="num">3</span><div><b>${ps.filter(p=>progressVal(p)>=45).length}</b><p>Autorizzabili</p></div></div><div class="step"><span class="num">4</span><div><b>${(state.data.practices||[]).filter(p=>owner(p)==='italy').length}</b><p>Trasferite Italy</p></div></div></div></section><div class="v26-layout"><div>${v27PracticeTable('Inbox e controllo documenti','Pratiche da agenti/clienti con azioni operative',ps)}</div><aside class="v26-grid">${quickActions('bangla')}${banglaWorkTools()}${membershipPanel()}${activityPanel()}</aside></div></div>`; }
  function italyDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${v27PracticeTable('Pratiche assegnate a Team Italy','Solo pratiche autorizzate e trasferite da Team Bangla.',ps)}${italyWorkflowTools(ps)}</div><aside class="v26-grid">${membershipPanel()}${quickActions('italy')}${deadlinesCard(ps)}</aside></div>`; }
  function commercialistaDashboard(ps){ return `<div class="v26-layout"><div class="v26-grid">${commercialistaOnboarding()}${v27PracticeTable('Pratiche fiscali recenti','Ditte, contabilità, F24 e documenti collegati',ps)}</div><aside class="v26-grid">${quickActions('commercialista')}${commercialistaPackages()}${documentsQuickPanel(ps)}</aside></div>`; }
  function pageContent(){ const role=state.session?.role||'admin'; const ps=rolePractices(role); if(state.page==='dashboard') return dashboard(); if(state.page==='create'||state.page==='company-new') return createPage(role); if(['clients','agents','users'].includes(state.page)) return clientsPage(role); if(state.page==='documents') return documentsPage(ps); if(state.page==='membership') return membershipPage(); if(['credit','wallet','commissioni'].includes(state.page)) return creditPage(); if(state.page==='daily') return dailyPage(); if(state.page==='tickets') return ticketsPage(); if(state.page==='settings') return settingsPage(); if(['reports','sales','invoices','f24','employees','packages','profile','notifications','commercialista-lead'].includes(state.page)) return modulePage(state.page, role, ps); if(['practices','assigned','agent-inbox','verify','transfers','review730','complete'].includes(state.page)) return `${v27Hero()}${v27PracticeTable(state.page==='assigned'?'Pratiche assegnate':'Pratiche operative','Dati reali dal backend, con upload, dettaglio e autorizzazioni.',ps)}`; if(state.page==='detail') return detailPage(state.detail); return `${v27Hero()}${v27PracticeTable('Modulo operativo','Sezione collegata al backend.',ps)}`; }
  function createPage(role){ const services=[['Modello 730','730','35','7','fa-file-invoice'],['ISEE Ordinario','ISEE','25','5','fa-file-lines'],['NASpI','NASPI','30','6','fa-briefcase'],['Assegno Unico','AU','25','5','fa-people-roof'],['Permesso Soggiorno','PDS','40','10','fa-id-card'],['Ricongiungimento','RICONG','60','15','fa-users'],['Cittadinanza','CITT','80','20','fa-passport'],['Partita IVA','PIVA','50','12','fa-building']]; return `${v27Hero()}<section class="v26-card v26-section v27-create"><div class="v26-section-head"><div><h2>Nuova pratica completa</h2><p>Servizio, cliente, documenti, calcolo profitto e assegnazione team.</p></div>${btn('<i class="fa-solid fa-magnifying-glass"></i> Cerca cliente salvato','light','data-page="clients"')}</div><div class="v27-wizard"><span class="active">1 Servizio</span><span>2 Cliente</span><span>3 Documenti</span><span>4 Calcolo</span><span>5 Conferma</span></div><div class="v26-service-grid" id="v26Services">${services.map((s,i)=>`<button type="button" class="v26-service ${i===0?'active':''}" data-service="${esc(s[1])}" data-title="${esc(s[0])}" data-price="${s[2]}" data-caf="${s[3]}"><i class="fa-solid ${s[4]}"></i><b>${esc(s[0])}</b><span>Cliente €${s[2]} · CAF €${s[3]} · Profitto €${Number(s[2])-Number(s[3])}</span></button>`).join('')}</div><form class="v26-form v27-form" id="v26CreateForm"><input type="hidden" name="service" value="730"><input type="hidden" name="serviceTitle" value="Modello 730"><input type="hidden" name="price" value="35"><input type="hidden" name="cafCost" value="7"><label>Nome cliente *<input name="firstName" required placeholder="Ali"></label><label>Cognome cliente *<input name="lastName" required placeholder="Hoq"></label><label>Email<input name="email" placeholder="cliente@email.com"></label><label>Telefono / WhatsApp<input name="phone" placeholder="+39..."></label><label>Codice fiscale<input name="cf" placeholder="CF cliente"></label><label>Team destinazione<select name="team"><option value="bangla">Team Bangla - primo controllo</option>${role==='admin'||role==='bangla'?'<option value="commercialista">Commercialista</option><option value="italy">Team Italy (solo autorizzato)</option>':''}</select></label><label>Cliente paga €<input name="clientPaid" type="number" value="35"></label><label>Costo CAF CAE €<input name="cafCostInput" type="number" value="7"></label><label>Profitto netto €<input name="profit" readonly value="28"></label><label class="wide">Documenti da richiedere / note<textarea name="note" placeholder="Documento identità, codice fiscale, CU, contratto, IBAN..."></textarea></label><div class="wide v27-submitbar"><button class="v26-btn orange" type="submit"><i class="fa-solid fa-paper-plane"></i> Salva pratica nel backend</button><button class="v26-btn light" type="button" data-page="documents"><i class="fa-solid fa-upload"></i> Carica documenti dopo salvataggio</button></div></form></section>`; }
  function clientsPage(role){ const rows=roleClients(role); return `${v27Hero()}${v27Panel('Database clienti','Salvati nel server: ricerca, auto-fill, storico pratiche, membership e documenti.', `<div class="v27-filterbar"><div class="v26-search"><i class="fa-solid fa-search"></i><input data-local-search placeholder="Cerca nome, CF, telefono, email..."></div>${btn('<i class="fa-solid fa-plus"></i> Nuovo cliente/pratica','orange','data-page="create"')}</div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Nome</th><th>CF</th><th>Telefono</th><th>Email</th><th>Ultima pratica</th><th>Azione</th></tr></thead><tbody>${v27ClientRows(rows)}</tbody></table></div>`)}`; }
  function documentsPage(ps){ return `${v27Hero()}${v27PracticeTable('Documenti, allegati e ricevute','Apri una pratica per anteprima/download/upload. I file sono salvati nel backend/Supabase.', ps, btn('<i class="fa-solid fa-upload"></i> Carica su pratica aperta','orange'))}${documentsQuickPanel(ps)}`; }
  function membershipPage(){ return `${v27Hero()}<div class="v26-layout"><div class="v26-grid">${membershipPanel()}${membershipTable()}</div><aside class="v26-grid">${v27Panel('Azioni membership','Crea, controlla risultato, rinnova e assegna team.', `<div class="v26-actions"><button class="v26-btn orange">Nuova membership</button><button class="v26-btn blue">Controlla risultato</button><button class="v26-btn green">Rinnova</button><button class="v26-btn light">Assegna team</button></div>`)}</aside></div>`; }
  function creditPage(){ const cr=state.data.credit||{}, role=state.session?.role; return `${v27Hero()}<div class="v26-layout"><div class="v26-grid">${agentProfitPanel(rolePractices())}${v27Panel(role==='admin'?'Richieste credito agenti':'Wallet e storico credito','Saldo, richieste, approvazioni e movimenti.', `<div class="v26-metrics v26-grid"><article class="v26-card v26-metric green"><div class="v26-ico"><i class="fa-solid fa-wallet"></i></div><span>Saldo disponibile</span><strong>${euro(cr.balance||0)}</strong><small>backend</small></article><article class="v26-card v26-metric orange"><div class="v26-ico"><i class="fa-solid fa-clock"></i></div><span>Movimenti</span><strong>${(cr.ledger||[]).length}</strong><small>storico</small></article></div><div class="v26-table-wrap"><table class="v26-table"><thead><tr><th>Data</th><th>Tipo</th><th>Importo</th><th>Motivo</th></tr></thead><tbody>${(cr.ledger||[]).map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${pill(x.type)}</td><td>${euro(x.amount)}</td><td>${esc(x.reason||'')}</td></tr>`).join('')||'<tr><td colspan="4"><div class="v26-empty">Nessun movimento reale.</div></td></tr>'}</tbody></table></div>`)}</div><aside>${agentCreditRequestBox()}${adminCreditRequests()}</aside></div>`; }
  function dailyPage(){ return `${v27Hero()}${v27Panel('Report giornaliero team','Team Bangla/Italy invia lavoro svolto ad Admin.', `<form class="v26-form" id="v26DailyForm"><label>Pratiche controllate<input name="checked" type="number" value="0"></label><label>Completate<input name="done" type="number" value="0"></label><label>Documenti richiesti<input name="missing" type="number" value="0"></label><label class="wide">Note lavoro<textarea name="notes" required placeholder="Cosa hai fatto oggi? problemi? pratiche urgenti?"></textarea></label><button class="v26-btn green" type="submit">Invia report ad Admin</button></form>`)}`; }
  function ticketsPage(){ return `${v27Hero()}${v27Panel('Ticket e problemi','Crea ticket verso Admin, Team o Commercialista.', `<form class="v26-form" id="v26TicketForm"><label>Oggetto<input name="subject" required placeholder="Problema pratica / documento"></label><label>Codice pratica<input name="practice_code" placeholder="CAF-..."></label><label>Destinatario<select name="target_role"><option value="admin">Admin</option><option value="bangla">Team Bangla</option><option value="italy">Team Italy</option><option value="commercialista">Commercialista</option></select></label><label class="wide">Messaggio<textarea name="message" required></textarea></label><button class="v26-btn orange" type="submit">Invia ticket</button></form>`)}`; }
  function detailPage(id){ const p=(state.data.practices||[]).find(x=>String(x.id)===String(id)||String(x.code)===String(id)); if(!p) return `${v27Hero()}<div class="v26-empty">Pratica non trovata</div>`; const hist=[...(p.workflow_events||p.workflowEvents||[]),...(p.team_history||p.teamHistory||[])].slice(0,10); return `${v27Hero()}<section class="v26-card v26-section v27-detail"><div class="v26-section-head"><div><h2>${esc(code(p))}</h2><p>${esc(clientName(p))} · ${esc(serviceName(p))}</p></div><div class="v26-hero-actions">${(owner(p)==='bangla'||state.session?.role==='admin')?btn('<i class="fa-solid fa-paper-plane"></i> Autorizza Team Italy','green',`data-authorize="${esc(p.id)}"`):''}${btn('<i class="fa-solid fa-upload"></i> Carica documenti','orange',`data-upload="${esc(p.id)}"`)}${btn('<i class="fa-solid fa-receipt"></i> Carica ricevuta','blue',`data-upload-receipt="${esc(p.id)}"`)}${btn('<i class="fa-solid fa-ticket"></i> Ticket','light','data-page="tickets"')}</div></div>${v27Tabs([['detail','Panoramica','fa-table'],['documents','Documenti','fa-folder-open'],['tickets','Ticket','fa-headset']])}<div class="v26-detail-grid"><div class="v26-card v26-section"><h3>Info cliente</h3><p><b>${esc(clientName(p))}</b></p><p>Email: ${esc(p.email||p.client?.email||'--')}</p><p>Tel: ${esc(p.phone||p.client?.phone||'--')}</p><p>CF: ${esc(p.cf||p.client?.cf||'--')}</p><p>Agent: ${esc(p.agent_email||p.agentEmail||'--')}</p></div><div class="v26-card v26-section"><h3>Pratica e documenti</h3><p>Servizio: <b>${esc(serviceName(p))}</b></p><p>Owner: <b>${esc(roleName(owner(p)))}</b></p><p>Stato: ${pill(p.status||'Nuova')}</p><p>Documenti: ${esc(p.document_status||p.documentStatus||'--')}</p>${progress(progressVal(p))}<div id="v26Files" class="v26-doc-list" style="margin-top:18px"><div class="v26-empty">Caricamento allegati...</div></div></div><div class="v26-card v26-section"><h3>Timeline live</h3><div class="v26-activity">${hist.map(h=>`<div class="v26-activity-item"><span class="dot"></span><div><b>${esc(h.action||h.message||'Update')}</b><span>${esc(h.by||h.actor_name||'Sistema')}</span></div><small>${esc(fmt(h.date||h.created_at))}</small></div>`).join('')||'<div class="v26-empty">Nessuna timeline</div>'}</div></div></div></section>`; }
  function settingsPage(){ return `${v27Hero()}${v27Panel('Servizi, prezzi, post e impostazioni','Admin può gestire catalogo servizi, prezzi, fonti/news e configurazioni.', `<div class="v27-action-grid"><button class="v26-btn orange">Nuovo servizio</button><button class="v26-btn blue">Aggiorna prezzo</button><button class="v26-btn green">Nuovo post/news</button><button class="v26-btn purple">Popup/ads</button><button class="v26-btn light">Fonti CAF</button><button class="v26-btn light">Permessi</button></div>`)}`; }
  function modulePage(page,role,ps){ const label=titleForPage(); return `${v27Hero()}<div class="v26-layout"><div>${v27PracticeTable(label,'Modulo operativo con dati reali e azioni collegate al backend.',ps)}</div><aside class="v26-grid">${quickActions(role)}${activityPanel()}</aside></div>`; }
  function agentProfitPanel(ps){ const total=ps.reduce((s,p)=>s+v27MoneyFromPractice(p),0), profit=ps.reduce((s,p)=>s+v27Profit(p),0), cost=total-profit; return v27Panel('Credito e profitto agente','Calcolo pratiche: cliente paga − costo CAF CAE = profitto.', `<div class="v27-profit-grid">${v27SmallCard('fa-cash-register','Totale incassato',euro(total),'reale','green')}${v27SmallCard('fa-building-columns','Costo pratiche',euro(cost),'CAF CAE','orange')}${v27SmallCard('fa-sack-dollar','Profitto netto',euro(profit),'agente','blue')}</div>`); }
  function agentCreditRequestBox(){ return v27Panel('Richiedi credito','Invia richiesta credito ad Admin con telefono e metodo pagamento.', `<form class="v26-form v27-mini-form" id="v27CreditForm"><label>Importo €<input name="amount" type="number" value="100"></label><label>Telefono<input name="phone" value="${esc(state.session?.phone||'')}"></label><label>Metodo<select name="payment_method"><option>Bonifico</option><option>Contanti</option><option>Postepay</option></select></label><label class="wide">Note<textarea name="note"></textarea></label><button class="v26-btn green" type="submit">Invia richiesta credito</button></form>`); }
  function adminCreditRequests(){ return v27Panel('Controllo credito agenti','Admin verifica richieste credito e approva dopo controllo.', `<div class="v26-empty">Le richieste reali appariranno qui. Sezione collegata a /api/v22/agent/credit-request.</div><button class="v26-btn green" data-page="credit">Apri credito agenti</button>`); }
  function adminTeamMonitor(){ const members=state.data.teamMembers||[]; return v27Panel('Team e assegnazioni','Gestisci dipendenti Team Bangla/Italy e owner pratica.', `<div class="v26-team-box">${['bangla','italy','commercialista'].map(r=>`<div class="v26-card"><b>${roleName(r)}</b><p>${members.filter(m=>m.team_role===r).length} membri</p><button class="v26-btn light" data-page="users">Gestisci</button></div>`).join('')}</div>`); }
  function banglaWorkTools(){ return v27Panel('Strumenti Team Bangla','Comunicazione cliente, documenti mancanti, report e assegnazione staff.', `<div class="v26-actions"><button class="v26-btn orange" data-page="verify">Richiedi documenti</button><button class="v26-btn blue" data-page="documents">Upload documenti</button><button class="v26-btn green" data-page="transfers">Autorizza Italy</button><button class="v26-btn light" data-page="daily">Report giornaliero</button></div>`); }
  function italyWorkflowTools(ps){ return v27Panel('Workflow pratica Team Italy','Ricevuta da Bangla → verifica → integrazione → controlli finali → completata.', `<div class="v26-flow"><div class="step"><span class="num">1</span><div><b>${ps.length}</b><p>Ricevute</p></div></div><div class="step"><span class="num">2</span><div><b>${ps.filter(p=>/verif|revision/i.test(p.status||'')).length}</b><p>Verifica</p></div></div><div class="step"><span class="num">3</span><div><b>${ps.filter(p=>/manc|integr/i.test(p.status||p.documentStatus||'')).length}</b><p>Integrazione</p></div></div><div class="step"><span class="num">4</span><div><b>${ps.filter(p=>/complet/i.test(p.status||'')).length}</b><p>Completate</p></div></div></div>`); }
  function commercialistaOnboarding(){ return v27Panel('Nuovo cliente / nuova ditta','Wizard commerciale: dati cliente, ditta, pacchetto, documenti e Shopify.', `<div class="v27-wizard"><span class="active">1 Dati cliente</span><span>2 Dati azienda</span><span>3 Servizi</span><span>4 Piano</span><span>5 Conferma</span></div><form class="v26-form"><label>Nome<input placeholder="Mario"></label><label>Cognome<input placeholder="Bianchi"></label><label>Email<input></label><label>Codice fiscale<input></label><label>Tipo cliente<select><option>Persona fisica</option><option>Ditta individuale</option><option>SRL</option></select></label><label>Piano<select><option>Base</option><option>Professional</option><option>Premium</option></select></label><button class="v26-btn orange" type="button">Salva cliente / ditta</button></form>`); }
  function commercialistaPackages(){ const packs=state.data.packages||[]; return v27Panel('Piani commercialista','Cosa è incluso e cosa no.', `<div class="v27-package-list">${(packs.length?packs:[{name:'Base',monthly_price:49},{name:'Professional',monthly_price:99},{name:'Premium',monthly_price:149}]).map(p=>`<div class="v26-card"><b>${esc(p.name||p.package_name)}</b><strong>${euro(p.monthly_price||p.price||0)}/mese</strong><small>Fatture · F24 · Documenti · Report</small></div>`).join('')}</div>`); }
  function documentsQuickPanel(ps){ return v27Panel('Documenti veloci','Upload, anteprima, download e ricevute.', `<div class="v26-actions"><button class="v26-btn orange" data-page="documents">Carica documenti</button><button class="v26-btn blue" data-page="documents">Carica ricevuta</button><button class="v26-btn light" data-page="practices">Apri pratica</button></div>`); }
  function shell(){ const sess=state.session||readSession()||{}; const role=sess.role||'admin'; const nav=navFor(role); return `<aside class="v26-sidebar"><div class="v26-brand"><span class="v26-logo-mark">C</span><div><strong>CAF CAE <span>Pro</span></strong><small>Servizi. Persone. Risultati.</small></div></div><div class="v26-user-mini"><span class="v26-avatar">${esc((sess.name||sess.email||role).slice(0,2).toUpperCase())}</span><div><b>${esc(sess.name||sess.email||'Utente')}</b><span>${esc(roleLabel(role))}</span></div></div><nav class="v26-nav"><div class="v26-nav-title">Menu operativo</div>${nav.map(([p,l,i])=>`<button data-page="${p}" class="${state.page===p?'active':''}"><i class="fa-solid ${i}"></i>${esc(l)}${p==='tickets'?'<span class="v26-badge">!</span>':''}</button>`).join('')}</nav><div class="v26-sidebar-footer"><b>CAF CAE Pro v32</b><br>Login funzionante + UI stabile</div></aside><main class="v26-main"><header class="v26-topbar"><button class="v26-menu-toggle" id="v26Menu"><i class="fa-solid fa-bars"></i></button><div class="v26-titlebox"><b>${esc(titleForPage())}</b><p>${esc(subtitleForRole(role))}</p></div><div class="v26-search"><i class="fa-solid fa-search"></i><input id="v26GlobalSearch" value="${esc(state.search)}" placeholder="Cerca pratiche, utenti, documenti, clienti..."></div><div class="v26-top-actions"><button class="v26-icon" data-page="notifications"><i class="fa-regular fa-bell"></i><em>${state.data.notifications?.length||0}</em></button><button class="v26-icon" data-page="tickets"><i class="fa-regular fa-message"></i></button><button class="v26-icon" data-page="settings"><i class="fa-solid fa-gear"></i></button><button class="v26-btn light v27-logout" data-logout><i class="fa-solid fa-right-from-bracket"></i> Logout</button><div class="v26-profile"><span class="v26-avatar">${esc((sess.name||role).slice(0,1).toUpperCase())}</span><div><b>${esc(sess.name||sess.email||'Utente')}</b><span>${esc(roleLabel(role))}</span></div></div></div></header><div class="v26-content" id="v26Content">${pageContent()}</div></main><input id="v26FileInput" type="file" multiple class="v26-hide">`; }
  function titleForPage(){ const p=state.page; const m={dashboard:'Dashboard',create:'Crea pratica',clients:'Clienti',agents:'Agenti',users:'Team & Permessi',practices:'Pratiche',assigned:'Pratiche assegnate','agent-inbox':'Inbox agenti',verify:'Verifica documenti',transfers:'Invio a Italy',review730:'730 Review',complete:'Da completare',documents:'Documenti',membership:'Membership Center',credit:'Credito agenti',wallet:'Wallet & credito',commissioni:'Profitto',tickets:'Ticket',daily:'Report giornaliero',detail:'Dettaglio pratica',settings:'Servizi & prezzi',reports:'Report','company-new':'Nuova ditta',invoices:'Fatturazione',f24:'F24 e contributi',employees:'Dipendenti',packages:'Piani e pacchetti',profile:'Profilo & Salary'}; return m[p]||p.replace(/-/g,' ').replace(/^./,c=>c.toUpperCase()); }
  document.addEventListener('click', e=>{ if(e.target.closest('[data-logout]')){ e.preventDefault(); performLogout(); } });
  document.addEventListener('submit', e=>{
    const form = e.target && e.target.closest && e.target.closest('#v31LoginForm,#v30LoginForm,#v29LoginForm,.v31-login-form,.v30-login-form,.v29-login-form');
    if(form){ e.preventDefault(); e.stopPropagation(); handleLoginForm(form); }
  }, true);
  document.addEventListener('click', e=>{
    const btn = e.target.closest && e.target.closest('#v31LoginBtn,#v30LoginBtn,#v29LoginBtn,[data-cae-login]');
    if(btn){
      const form = btn.closest('form') || document.getElementById('v31LoginForm') || document.getElementById('v30LoginForm') || document.getElementById('v29LoginForm');
      if(form){ e.preventDefault(); e.stopPropagation(); handleLoginForm(form); }
    }
  }, true);
  document.addEventListener('keydown', e=>{
    if(e.key === 'Enter'){
      const root = document.getElementById('caeV29LoginRoot');
      if(root && root.contains(document.activeElement)){
        const form = document.getElementById('v31LoginForm') || document.getElementById('v30LoginForm') || document.getElementById('v29LoginForm');
        if(form){ e.preventDefault(); handleLoginForm(form); }
      }
    }
  }, true);
  document.addEventListener('submit', e=>{ if(e.target.id==='v27CreditForm'){ e.preventDefault(); const fd=new FormData(e.target); api('/api/v22/agent/credit-request',{method:'POST',json:{amount:Number(fd.get('amount')||0),phone:fd.get('phone'),payment_method:fd.get('payment_method'),note:fd.get('note')}}).then(()=>{toast('Richiesta credito inviata ad Admin.'); return refresh();}).catch(err=>toast(err.message)); }});

  async function forceRender(){
    state.mounted = false;
    await mount().catch(()=>{});
    render();
    return true;
  }
  window.CAF_CAE_V26_SYNC = refresh;
  window.CAF_CAE_V26_RENDER = render;
  window.CAF_CAE_V27_SYNC = refresh;
  window.CAF_CAE_V27_RENDER = render;
  window.CAF_CAE_V28_SYNC = refresh;
  window.CAF_CAE_V28_RENDER = forceRender;
  window.CAF_CAE_V29_SYNC = refresh;
  window.CAF_CAE_V29_RENDER = forceRender;
  window.CAF_CAE_V29_LOGIN = showLogin;
  window.CAF_CAE_V29_LOGOUT = performLogout;
  window.CAF_CAE_V30_SYNC = refresh;
  window.CAF_CAE_V30_RENDER = forceRender;
  window.CAF_CAE_V30_LOGIN = showLogin;
  window.CAF_CAE_V30_LOGOUT = performLogout;
  window.CAF_CAE_V31_SYNC = refresh;
  window.CAF_CAE_V31_RENDER = forceRender;
  window.CAF_CAE_V31_LOGIN = showLogin;
  window.CAF_CAE_V31_LOGOUT = performLogout;
  window.CAF_CAE_V32_SYNC = refresh;
  window.CAF_CAE_V32_RENDER = forceRender;
  window.CAF_CAE_V32_LOGIN = showLogin;
  window.CAF_CAE_V32_LOGOUT = performLogout;
  window.addEventListener('cafcae:v27-force-render', forceRender);
  window.addEventListener('cafcae:v28-force-render', forceRender);
  const bootTimer=setInterval(()=>{ if(!state.mounted) mount().catch(()=>{}); else if(!$('#caeV26App')) render(); }, 500);
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>mount().catch(()=>{}),600));
  setTimeout(()=>mount().catch(()=>{}), 50);
})();
